---
title: "Ashwini_Final_report"
output: html_document
---

## Motivation:

  In 2020, the world entered into a pandemic and now two years later as we recover and try to move on with life, everything is different. The pandemic brought with it a new lens that showed disparities based on SES, geographical location, etc. that always existed but were never taken seriously. 
  

* [This article](https://doi.org/10.1186/s12939-021-01582-4) by Khanijahani et al. (2021) highlights how people of color and those from a low SES are at higher risk to contracting COVID-19.as such, public health professionals should be aware of such gaps and make it an effort to especially focus on these groups at higher risk 
* Spacial analysis is an extremely impactful analysis technique in public health to address major issues, including COVID. [This spacial analysis study](https://doi.org/10.1186/s12889-021-12267-6) done in Central Iran identified key districts that play a major role in the transmission of the virus and so will benefit greatly in interventions to prevent and control the spread. 


Our goal with this project was two fold: First we aimed to use the spacial analysis technique and apply it to understanding how COVID-19 is spatially auto-correlated across different counties in the State of New York. Second, we wanted to test whether health behaviors and socioeconomic (SES) factors are associated with COVID-19 changes in each county from 2020 to 2022.

Please watch our accompanying [screencast](ADD SCREENCAST LINK) to further understand our project. 
  
  
## Question development:

  Our project looked at the change in COVID-19 trends in New York State for each county, specifically how COVID-19 is spatially autocorrelated across the different counties. We also looked at whether health behaviors and socioeconomic (SES) factors are associated with this change in trends by county. These analyses can be helpful to public health officials in several ways:
  
  First, understanding the spatial patterns of COVID-19 trends can help public health officials to identify areas that are at higher risk for the spread of the virus. This information can be used to target interventions and resources to these areas in order to reduce the spread of COVID-19 and protect the health of the population.

  Second, examining the relationship between health behaviors and SES factors and the change in COVID-19 trend can help public health officials to identify potential risk factors for the spread of the virus. This information can be used to develop targeted interventions and policies that aim to reduce the risk of COVID-19 transmission by addressing these factors.

  Overall, studying the change in COVID-19 trend in New York State for each county, and examining spatial autocorrelation and the relationship with health behaviors and SES factors, can provide valuable insights. These discoveries can help public health officials to better understand the spread of COVID-19 and take effective action to reduce the risk of transmission in communities at higher risk and address persisting health disparities.


Citation:

Khanijahani, A., Iezadi, S., Gholipour, K. et al. A systematic review of racial/ethnic and socioeconomic disparities in COVID-19. Int J Equity Health 20, 248 (2021). https://doi.org/10.1186/s12939-021-01582-4


## Data Sources:

To conduct our analysis, we considered three publically available data sources:

1. US Census Bureau: Demographics

The US Census Bureau contains 


2. University of Wisconsin, Population Health Institute: New York State Health Ranking

We obtained data from the County Health Rankings & Roadmaps (CHR&R) program of the University of Wisconsin Population Health Institute. This data allows us to explore the county rankings in the State based on sub-factors of health such as Length of Life, Clinical Care, etc. We also considered health measures such as household income, segregation index, etc. as variables of interest for analysis. 



3. NY.gov: COVID-19 cases in New York from 2020-2022

The official website for the State of New York contains a COVID-19 information page which also includes publically available data on COVID-19 testing, cases, vaccinations, etc. We choose datasets that includes information on COVID-19 test, cases, and vaccinations that included the `county` variable to be able to explore the distributions of these variables across counties. 

link data???


## Data cleaning:



