---
title: "Code for EDA Plot"
output: github_document
date: "2022-12-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(plotly)
```

```{r}
<<<<<<< HEAD
plot_df = comb 
=======
plot_df = comb %>% 
  pivot_longer(health_beh_r:env_r,
               names_to = "rank_var",
               values_to = "rank") %>% 
  filter(year == "2021")

>>>>>>> e7217c88c34f44a9ac8dcb87accd555ccec30275
## Cases

#health
d_beh = plot_df %>% 
  filter(rank_var == "health_beh_r")

n_beh = 
d_beh %>%
  mutate(text_label = str_c("County: ", county, "\nRank: ", rank)) %>% 
  plot_ly(x = ~rank, y = ~n_cases, color = ~county, text = ~text_label, alpha = .5, 
          type = "scatter", mode = "markers", colors = "inferno")

#env
d_env = plot_df %>% 
  filter(rank_var == "env_r")

n_env =
d_env %>%
  mutate(text_label = str_c("County: ", county, "\nRank: ", rank)) %>% 
  plot_ly(x = ~rank, y = ~n_cases, color = ~county, text = ~text_label, alpha = .5, 
          type = "scatter", mode = "markers", colors = "inferno")

#cc
d_cc = plot_df %>% 
  filter(rank_var == "clinical_care_r")

n_cc =
d_cc %>%
  mutate(text_label = str_c("County: ", county, "\nRank: ", rank)) %>% 
  plot_ly(x = ~rank, y = ~n_cases, color = ~county, text = ~text_label, alpha = .5, 
          type = "scatter", mode = "markers", colors = "inferno")

#ses
d_ses = plot_df %>% 
  filter(rank_var == "ses_r")

n_ses =
d_ses %>%
  mutate(text_label = str_c("County: ", county, "\nRank: ", rank)) %>% 
  plot_ly(x = ~rank, y = ~n_cases, color = ~county, text = ~text_label, alpha = .5, 
          type = "scatter", mode = "markers", colors = "inferno")
```

