---
title: "Ashwini_exploratory plot"
author: "Ashwini Varghese"
date: "2022-12-04"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(lubridate)
library(Hmisc)
library(plotly)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}

ny_vax =
  read_csv("./grace/ny_covidvax.csv") %>% 
  janitor::clean_names() %>% 
  select(-region, -series_complete) %>% 
  rename(date = report_as_of) %>% 
  mutate(date = lubridate::mdy(date))


vax_plotly =
  ny_vax %>%
  filter(date == "2022-11-14") %>%
  mutate(county = fct_reorder(county, first_dose, .desc = TRUE)) %>%
  mutate(text_label = str_c("County: ", county, "\nVaccinations: ", first_dose)) %>% 
  plot_ly(x = ~county, 
          y = ~first_dose, 
          type = "bar", 
          text = ~text_label) |>
          layout(xaxis = list(title = "County in New York State"), 
                 yaxis = list(title = "Cumulative Number of People with at least one dose"),          
                 title = "Cumulative people with at least one dose of any COVID-19 vaccine by county by 11/14/2022")


vax_plotly

```



```{r}

ny_death =
  read_csv("./grace/ny_coviddeaths.csv") %>% 
  janitor::clean_names() %>%
  rename(date = report_date, n_fatality = place_of_fatality) %>% 
  mutate(date = lubridate::mdy(date)) %>%
  select(-deaths_by_county_of_residence) %>%
  filter(county != "Statewide Total")


deaths_plotly =
  ny_death %>%
  filter(date == "2022-11-14") %>%
  mutate(county = fct_reorder(county, n_fatality, .desc = TRUE)) %>% 
  mutate(text_label = str_c("County: ", county, "\nDeaths: ", n_fatality)) %>% 
  plot_ly(x = ~county, 
          y = ~n_fatality, 
          type = "bar", 
          text = ~text_label) |>
          layout(xaxis = list(title = "County in New York State"), 
                 yaxis = list(title = "Cumulative Number of Fatalities"),          
                 title = "Cumulative COVID-19 deaths by county by 11/14/2022")

deaths_plotly


```


