---
title: "EDA"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
    toc_depth: 4
    theme: lumen
---


```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(lubridate)
library(Hmisc)
library(plotly)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "100%")

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}
## Cases

#health
d_beh = plot_df %>% 
  filter(rank_var == "health_beh_r")

n_beh = 
d_beh %>%
  mutate(text_label = str_c("County: ", county, "\nRank: ", rank)) %>% 
  plot_ly(x = ~rank, y = ~n_cases, color = ~county, text = ~text_label, alpha = .5, 
          type = "scatter", mode = "markers", colors = "inferno")

#env
d_env = plot_df %>% 
  filter(rank_var == "env_r")

n_env =
d_env %>%
  mutate(text_label = str_c("County: ", county, "\nRank: ", rank)) %>% 
  plot_ly(x = ~rank, y = ~n_cases, color = ~county, text = ~text_label, alpha = .5, 
          type = "scatter", mode = "markers", colors = "inferno")

#cc
d_cc = plot_df %>% 
  filter(rank_var == "clinical_care_r")

n_cc =
d_cc %>%
  mutate(text_label = str_c("County: ", county, "\nRank: ", rank)) %>% 
  plot_ly(x = ~rank, y = ~n_cases, color = ~county, text = ~text_label, alpha = .5, 
          type = "scatter", mode = "markers", colors = "inferno")

#ses
d_ses = plot_df %>% 
  filter(rank_var == "ses_r")

n_ses =
d_ses %>%
  mutate(text_label = str_c("County: ", county, "\nRank: ", rank)) %>% 
  plot_ly(x = ~rank, y = ~n_cases, color = ~county, text = ~text_label, alpha = .5, 
          type = "scatter", mode = "markers", colors = "inferno")
```




