<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Final Report</title>

<script src="site_libs/header-attrs-2.17/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/lumen.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<script src="site_libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<script src="site_libs/plotly-binding-4.10.0/plotly.js"></script>
<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>
<link href="site_libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="site_libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>
<link href="site_libs/plotly-htmlwidgets-css-2.5.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="site_libs/plotly-main-2.5.1/plotly-latest.min.js"></script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Project Overview</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="Final-Report-Main.html">Final Report</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="EDA.html">Exploratory Analysis</a>
</li>
<li>
  <a href="https://jagjit-singh.shinyapps.io/spatial/">Shiny App</a>
</li>
<li>
  <a href="data.html">Statistical Analysis</a>
</li>
<li>
  <a href="Autoregression.html">Autoregressive Analysis</a>
</li>
<li>
  <a href="data.html">Screencast</a>
</li>
<li>
  <a href="mailto:&lt;js5958@cumc.columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/jsingh-604/p8105_final_project/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Final Report</h1>

</div>


<div id="motivation" class="section level2">
<h2>Motivation</h2>
<p>In 2020, the world entered into a pandemic and now two years later as
we recover and try to move on with life, things are different. The
pandemic brought with it a new lens that showed disparities based on
SES, geographical location, etc. that always existed but were never
taken seriously. Research has shown that people of color and those from
a low SES are at higher risk to contracting COVID-19; as such, public
health professionals should be aware of such gaps and make it an effort
to especially focus on these groups at higher risk (Khanijahani et al.,
2021).</p>
</div>
<div id="analysis-and-relevance" class="section level2">
<h2>Analysis and Relevance:</h2>
<p>Our project looks at the change in COVID-19 trends in New York State
for each county, specifically how COVID-19 is spatially autocorrelated
across the different counties and the extent auto-correlation within New
York City, the most populated county. We also looked at whether health
behaviors and socioeconomic (SES) factors are associated with this
change in trends by county. These analyses can be helpful to public
health officials in the following ways:</p>
<p>First, understanding the spatial patterns of COVID-19 trends can help
public health officials to identify areas that are at higher risk for
the spread of the virus. This information can be used to target
interventions and resources to these areas in order to reduce the spread
of COVID-19 and protect the health of the population.</p>
<p>Second, examining the relationship between health behaviors and SES
factors and the change in COVID-19 trend can help public health
officials to identify potential risk factors for the spread of the
virus. This information can be used to develop targeted interventions
and policies that aim to reduce the risk of COVID-19 transmission by
addressing these factors.</p>
<p>Overall, studying the change in COVID-19 trend in New York State for
each county, and examining spatial autocorrelation and the relationship
with health behaviors and SES factors, can provide valuable insights.
These discoveries can help public health officials to better understand
the spread of COVID-19 and take effective action to reduce the risk of
transmission in communities at higher risk and address presisting health
disparities.</p>
</div>
<div id="data-processing-and-cleaning" class="section level2">
<h2>Data Processing and Cleaning</h2>
<div id="data-sources" class="section level3">
<h3>Data Sources</h3>
<p>Our data were downloaded from four different sources:</p>
<ol style="list-style-type: decimal">
<li><p><strong>New York State Demographics</strong>: US Census Bureau’s
demographics data were imported using <code>tidycensus</code>.</p></li>
<li><p><strong>New York State, County Land Area</strong> <a
href="https://www.health.ny.gov/statistics/vital_statistics/2010/table02.htm">(dataset)</a>
A .csv file was created based on the information provided in the
website.<br />
Note: unable to be loaded using <code>read_html</code> as this is an xml
document.</p></li>
<li><p><strong>New York State Health Ranking</strong> <a
href="https://www.countyhealthrankings.org/explore-health-rankings/new-york/data-and-resources">(dataset)</a>:
Four data sets (2019, 2020, 2021 and 2022 New York State Health Ranking
Data) were downloaded as .xls/xlsx. These data sets are provided by the
University of Wisconsin Population Health Institute, which performs
extensive analyses to calculate each New York county’s score for health
factors (health behaviors, clinical care, SES factors, and physical
environment) and health outcome (quality of life, and length of
life).</p></li>
<li><p><strong>New York State COVID-19</strong> <a
href="https://data.ny.gov/browse?tags=covid-19">(dataset)</a>: Three
data sets (COVID testing, COVID vaccination, COVID fatalities from 2020
to 11/2022) were downloaded as .csv.</p></li>
</ol>
</div>
<div id="data-cleaning" class="section level3">
<h3>Data Cleaning</h3>
<ol style="list-style-type: decimal">
<li><strong>New York State Demographics</strong><br />
We imported US Census Bureau’s 2020 data because 2021 data are not
available until 12/8/2022. As demographics data do not change
significantly each year, 2020 data were used for analysis. Then we
decided to include the following variables, as we would like to adjust
them in our models:</li>
</ol>
<ul>
<li>total population in each county (tpop)</li>
<li>median age in each county (medage)</li>
<li>racial diversity index (race_div): calculated Simpson’s Diversity
Index in lines 65 to 69 (higher index indicates more racial
diversity)</li>
</ul>
<pre class="r"><code>census_api_key(&quot;aa512886c5449a582d837da8d3a07af66a043fe5&quot;)

census_data &lt;- load_variables(2020, &quot;acs5&quot;, cache=T)
fwrite(census_data, &quot;census_variables.csv&quot;)

vars &lt;- c(tpop = &#39;P001001&#39;,
          medage = &#39;P013001&#39;,
          wpop = &#39;P003002&#39;,
          bpop = &#39;P003003&#39;,
          apop = &#39;P003005&#39;,
          hpop = &#39;P004003&#39;)

nys_df &lt;- get_decennial(state = &quot;ny&quot;, 
                       geography = &quot;county&quot;,
                       variables = vars,
                       geometry = T,
                       output = &quot;wide&quot;)

NY_df &lt;- get_decennial(state = &quot;ny&quot;, 
                       geography = &quot;county&quot;,
                       variables = vars,
                       geometry = T,
                       output = &quot;wide&quot;)

NY_df = NY_df %&gt;%
  mutate(
    county = gsub(&quot; County, New York&quot;,&quot;&quot;,NAME))

nys_df = nys_df %&gt;%
  mutate(
    county = gsub(&quot; County, New York&quot;,&quot;&quot;,NAME))

nys_df$race_div &lt;- 1 - (((nys_df$wpop*(nys_df$wpop-1))+
                          (nys_df$bpop*(nys_df$bpop-1))+
                          (nys_df$hpop*(nys_df$hpop-1))+
                          (nys_df$apop*(nys_df$apop-1)))/
                         (nys_df$tpop*(nys_df$tpop-1)))

nys_df = nys_df %&gt;% 
  select(tpop, medage, county, race_div)</code></pre>
<ol start="2" style="list-style-type: decimal">
<li><strong>New York State, County Land Area</strong> After loading the
dataset, which only contains two variables–county and value (provides
area of each county as square mile; this variable was renamed as
“area”)–the dataset was merged with nys_df to calculate population
density for each county. The population density variable was created so
we can adjust for it in our regression models, especially ones that
involve number of COVID-19 cases and fatalities.</li>
</ol>
<pre class="r"><code>area = read_excel(&#39;data/pop_density.xlsx&#39;) %&gt;% 
  janitor::clean_names() %&gt;% 
  rename(area = value)

nys_df = left_join(nys_df, area, by = &#39;county&#39;) %&gt;% 
  mutate(pop_d = tpop/area)</code></pre>
<ol start="3" style="list-style-type: decimal">
<li><strong>New York State Health Ranking</strong><br />
Same steps were taken for each year except 2019; for this year, the
sub-variables from the “Ranked Measure Data” sheet were labeled slightly
different compared to the follow years so for consistency, each of the
successive years, the variables needed to be renamed to match the
original names from the 2019 dataset: As the original excel files
contain multiple sheets. We only imported the sheets that contain
variables of interest.<br />
<br>Each county’s health ranking was imported from the sheet named
“Outcomes &amp; Factors SubRankings.” From the sheet, only the following
variables were selected for future analysis: each county’s rank for
health outcomes (quality of life, renamed to qol_r; length of life,
renamed to longevity_r), health factors (health behaviors, renamed to
health_beh_r; clinical_care, renamed to clinical_care_r; socioeconomic
factors, renamed to ses_r; physical environment, renamed to env_r).
<br>Additionally, further information on each county’s socioeconomic
factors and race/ethnicity were imported from the sheet named
“Additional Measure Data.” The following variables were selected: each
county’s segregation index (white vs. nonwhite), renamed to
segregation_score; median household income, renamed household_income; %
Hispanic, p_hispanic; % black, renamed p_black). As we are interested in
observing racial and socioeconomic disparities in COVID, we then created
the following variables: % minority (hispanic + black), named
p_minority; binary variable for low vs. moderate/high level of
segregation. The cutoff value for level of segregation was set as 30. <a
href="https://www1.udel.edu/uapp800/Lecture%20Material/Index%20of%20Dissimilarity%20Example.htm">(source)</a>
<br>Lastly, we imported data from the sheet labeled “Ranked Measure
Data” to import the sub-variables that make up the Health Behaviors
Ranking. We imported the variables county, percent of smokers, percent
of adults with obesity, food environment index (0-10 with 10 as the
best), percent of adults who are physically inactive, percent of adults
with access to location with opportunities to exercise, percent of
adults who report excessive drinking, percent of driving related deaths
with alcohol involved, the number of chlamydia cases, and the teen birth
rate per every 1000 females aged 15-19.</li>
</ol>
<pre class="r"><code># 2019 HR Data

hr2019 = read_excel(&#39;data/ny_hr19.xls&#39;, 
                    sheet = &#39;Outcomes &amp; Factors SubRankings&#39;, skip = 1) %&gt;% 
  janitor::clean_names() %&gt;% 
  slice(-c(1)) %&gt;% 
  select(-starts_with(&quot;z&quot;), -fips, -state) %&gt;% 
  rename(longevity_r = rank_5,
         qol_r = rank_7,
         health_beh_r = rank_9,
         clinical_care_r = rank_11,
         ses_r = rank_13,
         env_r = rank_15)

demo2019 = read_excel(&#39;data/ny_hr19.xls&#39;, 
                      sheet = &#39;Additional Measure Data&#39;, skip = 1) %&gt;% 
  janitor::clean_names() %&gt;% 
  slice(-c(1)) %&gt;% 
  select(&#39;county&#39;, 
         &#39;segregation_index_2&#39;,
         &#39;household_income&#39;,
         &#39;percent_hispanic&#39;,
         &#39;percent_african_american&#39;) %&gt;% 
  rename(median_income = household_income,
         segregation_score = segregation_index_2,
         p_hispanic = percent_hispanic,
         p_black = percent_african_american) %&gt;%
    mutate(segregation = case_when(segregation_score &lt; 30 ~ 0,
                                 segregation_score &gt;= 30 ~ 1),
           p_minority = p_black + p_hispanic)

sub_var19 =
  read_excel(&#39;data/ny_hr19.xls&#39;, sheet = &#39;Ranked Measure Data&#39;, skip = 1) %&gt;% 
  janitor::clean_names() %&gt;% 
  slice(-c(1)) %&gt;%
  select(county, percent_smokers, percent_obese, food_environment_index, percent_physically_inactive, percent_with_access, percent_excessive_drinking, percent_alcohol_impaired, number_chlamydia_cases, teen_birth_rate, percent_unemployed)
  

list_2019 =
  list(hr2019, demo2019, sub_var19)

total2019 = 
  list_2019 %&gt;%
  reduce(full_join, by = &quot;county&quot;) %&gt;%
  mutate(year = 2019)

# 2020 HR Data
hr2020 = read_excel(&#39;data/ny_hr20.xlsx&#39;, 
                    sheet = &#39;Outcomes &amp; Factors SubRankings&#39;, skip = 1) %&gt;% 
  janitor::clean_names() %&gt;% 
  slice(-c(1)) %&gt;% 
  select(-starts_with(&quot;z&quot;), -fips, -state) %&gt;% 
  rename(longevity_r = rank_5,
         qol_r = rank_7,
         health_beh_r = rank_9,
         clinical_care_r = rank_11,
         ses_r = rank_13,
         env_r = rank_15)

demo2020 = read_excel(&#39;data/ny_hr20.xlsx&#39;, 
                      sheet = &#39;Additional Measure Data&#39;, skip = 1) %&gt;% 
  janitor::clean_names() %&gt;% 
  slice(-c(1)) %&gt;% 
  select(&#39;county&#39;, 
         &#39;median_household_income&#39;, 
         &#39;segregation_index_2&#39;,
         &#39;percent_black&#39;,
         &#39;percent_hispanic&#39;) %&gt;% 
  rename(median_income = median_household_income, 
         segregation_score = segregation_index_2,
         p_black = percent_black,
         p_hispanic = percent_hispanic) %&gt;% 
    mutate(segregation = case_when(segregation_score &lt; 30 ~ 0,
                                 segregation_score &gt;= 30 ~ 1),
           p_minority = p_black + p_hispanic)

sub_var20 =
  read_excel(&#39;data/ny_hr20.xlsx&#39;, sheet = &#39;Ranked Measure Data&#39;, skip = 1) %&gt;% 
  janitor::clean_names() %&gt;% 
  slice(-c(1)) %&gt;%
  select(county, percent_smokers, percent_adults_with_obesity, food_environment_index, percent_physically_inactive, percent_with_access_to_exercise_opportunities, percent_excessive_drinking, percent_driving_deaths_with_alcohol_involvement, number_chlamydia_cases, teen_birth_rate, percent_unemployed) %&gt;%
  rename(percent_obese = percent_adults_with_obesity,
         percent_with_access = percent_with_access_to_exercise_opportunities,
         percent_alcohol_impaired = percent_driving_deaths_with_alcohol_involvement)
  

list_2020 =
  list(hr2020, demo2020, sub_var20)

total2020 = 
  list_2020 %&gt;%
  reduce(full_join, by = &quot;county&quot;) %&gt;%
  mutate(year = 2020)

# 2021 HR Data
hr2021 = read_excel(&#39;data/ny_hr21.xlsx&#39;, 
                    sheet = &#39;Outcomes &amp; Factors SubRankings&#39;, skip = 1) %&gt;% 
  janitor::clean_names() %&gt;% 
  slice(-c(1)) %&gt;% 
  select(-starts_with(&quot;z&quot;), -fips, -state) %&gt;% 
  rename(longevity_r = rank_5,
         qol_r = rank_7,
         health_beh_r = rank_9,
         clinical_care_r = rank_11,
         ses_r = rank_13,
         env_r = rank_15)

demo2021 = read_excel(&#39;data/ny_hr21.xlsx&#39;, 
                      sheet = &#39;Additional Measure Data&#39;, skip = 1) %&gt;% 
  janitor::clean_names() %&gt;% 
  slice(-c(1)) %&gt;% 
  select(&#39;county&#39;, 
         &#39;median_household_income&#39;, 
         &#39;segregation_index_2&#39;,
         &#39;percent_black&#39;,
         &#39;percent_hispanic&#39;) %&gt;% 
  rename(median_income = median_household_income, 
         segregation_score = segregation_index_2,
         p_black = percent_black,
         p_hispanic = percent_hispanic) %&gt;% 
    mutate(segregation = case_when(segregation_score &lt; 30 ~ 0,
                                 segregation_score &gt;= 30 ~ 1),
           p_minority = p_black + p_hispanic)

sub_var21 =
  read_excel(&#39;data/ny_hr21.xlsx&#39;, sheet = &#39;Ranked Measure Data&#39;, skip = 1) %&gt;% 
  janitor::clean_names() %&gt;% 
  slice(-c(1)) %&gt;%
  select(county, percent_smokers, percent_adults_with_obesity, food_environment_index, percent_physically_inactive, percent_with_access_to_exercise_opportunities, percent_excessive_drinking, percent_driving_deaths_with_alcohol_involvement, number_chlamydia_cases, teen_birth_rate, percent_unemployed) %&gt;%
  rename(percent_obese = percent_adults_with_obesity,
         percent_with_access = percent_with_access_to_exercise_opportunities,
         percent_alcohol_impaired = percent_driving_deaths_with_alcohol_involvement)

list_2021 =
  list(hr2021, demo2021, sub_var21)

total2021 = 
  list_2021 %&gt;%
  reduce(full_join, by = &quot;county&quot;) %&gt;%
  mutate(year = 2021)

# 2022 HR Data
hr2022 = read_excel(&#39;data/ny_hr22.xlsx&#39;, 
                    sheet = &#39;Outcomes &amp; Factors SubRankings&#39;, skip = 1) %&gt;% 
  janitor::clean_names() %&gt;% 
  slice(-c(1)) %&gt;% 
  select(-starts_with(&quot;z&quot;), -fips, -state) %&gt;% 
  rename(longevity_r = rank_5,
         qol_r = rank_7,
         health_beh_r = rank_9,
         clinical_care_r = rank_11,
         ses_r = rank_13,
         env_r = rank_15)

demo2022 = read_excel(&#39;data/ny_hr22.xlsx&#39;, 
                      sheet = &#39;Additional Measure Data&#39;, skip = 1) %&gt;% 
  janitor::clean_names() %&gt;% 
  slice(-c(1)) %&gt;% 
    select(&#39;county&#39;, 
         &#39;median_household_income&#39;, 
         &#39;segregation_index&#39;,
         &#39;percent_black&#39;,
         &#39;percent_hispanic&#39;) %&gt;% 
  rename(median_income = median_household_income, 
         segregation_score = segregation_index,
         p_black = percent_black,
         p_hispanic = percent_hispanic) %&gt;% 
    mutate(segregation = case_when(segregation_score &lt; 30 ~ 0,
                                 segregation_score &gt;= 30 ~ 1),
           p_minority = p_hispanic + p_black)

sub_var22 =
  read_excel(&#39;data/ny_hr22.xlsx&#39;, sheet = &#39;Ranked Measure Data&#39;, skip = 1) %&gt;% 
  janitor::clean_names() %&gt;% 
  slice(-c(1)) %&gt;%
  select(county, percent_smokers, percent_adults_with_obesity, food_environment_index, percent_physically_inactive, percent_with_access_to_exercise_opportunities, percent_excessive_drinking, percent_driving_deaths_with_alcohol_involvement, number_chlamydia_cases, teen_birth_rate, percent_unemployed) %&gt;%
  rename(percent_obese = percent_adults_with_obesity,
         percent_with_access = percent_with_access_to_exercise_opportunities,
         percent_alcohol_impaired = percent_driving_deaths_with_alcohol_involvement)

list_2022 =
  list(hr2022, demo2022, sub_var22)

total2022 = 
  list_2022 %&gt;%
  reduce(full_join, by = &quot;county&quot;) %&gt;%
  mutate(year = 2022)

# Merge
hr_all = rbind(total2019, total2020, total2021, total2022)</code></pre>
<ol start="3" style="list-style-type: decimal">
<li><strong>New York State COVID-19</strong><br />
From the three data sets we extracted the following variables of
interest: number of new COVID cases per day, cumulative number of deaths
reported per day, cumulative # of individuals who received the first
dose of the vaccine. For the data set with cumulative number of deaths,
the county “Manhattan” was replaced with “New York” for consistency.
Next, the three data sets were merged by “date” and “county.” The merged
data set was then grouped according to “county” and “year” and the
following variables were created: total number of new positive cases per
year, called n_cases; total number of deaths per year, called n_deaths;
and total number of individuals who received the first dose of the
vaccine per year, called vax_dose1 (this data is not available for year
2020).</li>
</ol>
<pre class="r"><code>ny_test = read_csv(&#39;data/ny_covidtest.csv&#39;) %&gt;% 
janitor::clean_names() %&gt;% 
filter(geography == &#39;COUNTY&#39;) %&gt;% 
select(-geography) %&gt;% 
rename(date = test_date) %&gt;% 
mutate(date = lubridate::mdy(date))  

ny_death = read_csv(&quot;data/ny_coviddeaths.csv&quot;) %&gt;% 
janitor::clean_names() %&gt;% 
rename(date = report_date, n_fatality = place_of_fatality) %&gt;%
select(-deaths_by_county_of_residence) %&gt;% 
mutate(date = lubridate::mdy(date), 
       county = replace(county, county == &#39;Manhattan&#39;, &#39;New York&#39;))

ny_vax = read_csv(&quot;data/ny_covidvax.csv&quot;) %&gt;% 
janitor::clean_names() %&gt;% 
rename(date = report_as_of) %&gt;% 
select(-region, -series_complete) %&gt;% 
mutate(date = lubridate::mdy(date))

ny_covid_v1 = left_join(ny_test, ny_death, by = c(&quot;date&quot;, &quot;county&quot;))

covid_df_v1 = left_join(ny_covid_v1, ny_vax, by = c(&quot;date&quot;, &quot;county&quot;)) %&gt;% 
  separate(date, c(&quot;year&quot;, &quot;month&quot;, &quot;day&quot;), sep = &quot;-&quot;) %&gt;% 
  mutate(year = as.numeric(year), 
         month = as.numeric(month), 
         day = as.numeric(day))

covid_df = covid_df_v1 %&gt;% 
  group_by(year, county) %&gt;% 
  summarise(n_cases = sum(new_positives),
            vax_dose1 = max(first_dose),
            n_deaths = max(n_fatality, na.rm = TRUE))</code></pre>
<ol start="4" style="list-style-type: decimal">
<li><strong>Dataset for Analysis</strong><br />
For the first section of regression tests, the demographics dataset, HR
dataset, and COVID dataset were merged into one dataset called “comb.”
At the end, we added a new binary variable called vax_maj to see whether
majority of the residents in the county had received the first dose of
vaccine. The cutoff value used was 79% as it was reported that nearly
~79% of the US population had completed at least one dose of vaccine by
the end of 2022. <a
href="https://usafacts.org/visualizations/covid-vaccine-tracker-states/state/new-york">(source)</a></li>
</ol>
<pre class="r"><code>covid_hr = left_join(covid_df, hr_all, by = c(&quot;county&quot;, &quot;year&quot;)) 
comb = left_join(covid_hr, nys_df, by = &#39;county&#39;) %&gt;% 
  mutate(tpop_50 = tpop/2,
         vax_maj = case_when(vax_dose1 &gt;= .83*(tpop) ~ 1,
                             vax_dose1 &lt; .83*(tpop) ~ 0))</code></pre>
<ol start="5" style="list-style-type: decimal">
<li><strong>Dataset for Additional Analysis </strong><br />
For the additional regression analysis section, in order to have a more
focused dataset, a new dataset was created that is a combination of the
Census demographics, NY COVID data, and the Sub-variables dataset from
the “Ranked Measure Data” sheet for each of the four Health Ranking
datasets.</li>
</ol>
<pre class="r"><code>sub_var_data =
  hr_all %&gt;%
  select(-ends_with(&quot;_r&quot;))

covid_hr = left_join(covid_df, sub_var_data, by = c(&quot;county&quot;, &quot;year&quot;)) 

new_comb = left_join(covid_hr, nys_df, by = &#39;county&#39;)</code></pre>
<ol start="5" style="list-style-type: decimal">
<li><strong>Bubble Plot</strong><br />
We were interested in seeing whether there is a correlation between SES
factors ranking and health behaviors and how it varies by the total
number of residents in each county.</li>
</ol>
<pre class="r"><code>bubble_df = comb %&gt;% 
  select(year, county, health_beh_r, ses_r, tpop) %&gt;% 
  filter(year == &#39;2021&#39;)</code></pre>
<ol start="6" style="list-style-type: decimal">
<li><strong>Bar Graphs for EDA</strong><br />
County health factors ranking (HR) was categorized into 4 quartiles
quartile 1 = ranks 1 to 16; quartile 2 = ranks 17 to 31; quartile 3 =
ranks 32 to 46, quartile 4 = ranks 47 to 62).<a
href="https://www.countyhealthrankings.org/reports/state-reports/2022-new-york-state-report">(source)</a>
To observe any patterns between HR and COVID.</li>
</ol>
<pre class="r"><code>eda1 = comb %&gt;% 
  pivot_longer(health_beh_r:env_r,
               names_to = &quot;rank_var&quot;,
               values_to = &quot;rank&quot;) %&gt;% 
  filter(year == &#39;2021&#39;) %&gt;% 
  mutate(quartile = case_when(rank &lt; 17 ~ &#39;q1&#39;,
                              rank &lt; 32 ~ &#39;q2&#39;,
                              rank &lt; 46 ~ &#39;q3&#39;,
                              rank &lt; 63 ~ &#39;q4&#39;)) %&gt;% 
  mutate(quartile = as.factor(quartile))</code></pre>
</div>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p>In order to have a better understanding of the existing socioeconomic
and health factor status of the counties we conducted some exploratory
data analysis mainly through visualization. We first tried to see which
counties have the highest socio-economic and heath factor scores</p>
<pre class="r"><code>library(plotly)
data = bubble_df %&gt;%
  mutate(county = as.factor(county),
         health_beh_r = as.numeric(health_beh_r),
         ses_r = as.numeric(ses_r)) %&gt;%
  janitor::clean_names()


total &lt;- merge(bubble_df,NY_df,by=&quot;county&quot;)

fig &lt;- plot_ly(total, x = ~health_beh_r, y = ~ses_r, text = ~county, type = &#39;scatter&#39;,
               mode = &#39;markers&#39;, size = ~tpop.y, color = ~county, colors = &#39;Paired&#39;,
               marker = list(opacity = 0.5, sizemode = &#39;diameter&#39;))

fig &lt;- fig %&gt;% layout(title = &#39;Bubble Plot (Bubble Size = County Population)&#39;,
                      xaxis = list(title = &#39;Health Score&#39;),
                      yaxis = list(title = &#39;Socio-economic Score&#39;),
                      showlegend = FALSE)

fig</code></pre>
<div id="htmlwidget-11bd044f21d23b7187e4" style="width:90%;height:576px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-11bd044f21d23b7187e4">{"x":{"visdat":{"ebb52ef62c0c":["function () ","plotlyVisDat"]},"cur_data":"ebb52ef62c0c","attrs":{"ebb52ef62c0c":{"x":{},"y":{},"text":{},"mode":"markers","marker":{"opacity":0.5,"sizemode":"diameter"},"color":{},"size":{},"colors":"Paired","alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Bubble Plot (Bubble Size = County Population)","xaxis":{"domain":[0,1],"automargin":true,"title":"Health Score"},"yaxis":{"domain":[0,1],"automargin":true,"title":"Socio-economic Score"},"showlegend":false,"hovermode":"closest"},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":[13],"y":[7],"text":"Albany","mode":"markers","marker":{"color":"rgba(166,206,227,1)","size":[20.7778343141867],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(166,206,227,1)"}},"type":"scatter","name":"Albany","textfont":{"color":"rgba(166,206,227,1)","size":20.7778343141867},"error_y":{"color":"rgba(166,206,227,1)","width":20.7778343141867},"error_x":{"color":"rgba(166,206,227,1)","width":20.7778343141867},"line":{"color":"rgba(166,206,227,1)","width":20.7778343141867},"xaxis":"x","yaxis":"y","frame":null},{"x":[47],"y":[53],"text":"Allegany","mode":"markers","marker":{"color":"rgba(146,190,219,1)","size":[11.5880463897236],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(146,190,219,1)"}},"type":"scatter","name":"Allegany","textfont":{"color":"rgba(146,190,219,1)","size":11.5880463897236},"error_y":{"color":"rgba(146,190,219,1)","width":11.5880463897236},"error_x":{"color":"rgba(146,190,219,1)","width":11.5880463897236},"line":{"color":"rgba(146,190,219,1)","width":11.5880463897236},"xaxis":"x","yaxis":"y","frame":null},{"x":[28],"y":[62],"text":"Bronx","mode":"markers","marker":{"color":"rgba(126,174,210,1)","size":[59.6924952717428],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(126,174,210,1)"}},"type":"scatter","name":"Bronx","textfont":{"color":"rgba(126,174,210,1)","size":59.6924952717428},"error_y":{"color":"rgba(126,174,210,1)","width":59.6924952717428},"error_x":{"color":"rgba(126,174,210,1)","width":59.6924952717428},"line":{"color":"rgba(126,174,210,1)","width":59.6924952717428},"xaxis":"x","yaxis":"y","frame":null},{"x":[35],"y":[48],"text":"Broome","mode":"markers","marker":{"color":"rgba(104,158,202,1)","size":[17.0478874050748],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(104,158,202,1)"}},"type":"scatter","name":"Broome","textfont":{"color":"rgba(104,158,202,1)","size":17.0478874050748},"error_y":{"color":"rgba(104,158,202,1)","width":17.0478874050748},"error_x":{"color":"rgba(104,158,202,1)","width":17.0478874050748},"line":{"color":"rgba(104,158,202,1)","width":17.0478874050748},"xaxis":"x","yaxis":"y","frame":null},{"x":[60],"y":[51],"text":"Cattaraugus","mode":"markers","marker":{"color":"rgba(81,143,193,1)","size":[12.7174638300324],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(81,143,193,1)"}},"type":"scatter","name":"Cattaraugus","textfont":{"color":"rgba(81,143,193,1)","size":12.7174638300324},"error_y":{"color":"rgba(81,143,193,1)","width":12.7174638300324},"error_x":{"color":"rgba(81,143,193,1)","width":12.7174638300324},"line":{"color":"rgba(81,143,193,1)","width":12.7174638300324},"xaxis":"x","yaxis":"y","frame":null},{"x":[46],"y":[41],"text":"Cayuga","mode":"markers","marker":{"color":"rgba(53,128,185,1)","size":[12.7069872601069],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(53,128,185,1)"}},"type":"scatter","name":"Cayuga","textfont":{"color":"rgba(53,128,185,1)","size":12.7069872601069},"error_y":{"color":"rgba(53,128,185,1)","width":12.7069872601069},"error_x":{"color":"rgba(53,128,185,1)","width":12.7069872601069},"line":{"color":"rgba(53,128,185,1)","width":12.7069872601069},"xaxis":"x","yaxis":"y","frame":null},{"x":[54],"y":[50],"text":"Chautauqua","mode":"markers","marker":{"color":"rgba(58,128,177,1)","size":[14.6827387409875],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(58,128,177,1)"}},"type":"scatter","name":"Chautauqua","textfont":{"color":"rgba(58,128,177,1)","size":14.6827387409875},"error_y":{"color":"rgba(58,128,177,1)","width":14.6827387409875},"error_x":{"color":"rgba(58,128,177,1)","width":14.6827387409875},"line":{"color":"rgba(58,128,177,1)","width":14.6827387409875},"xaxis":"x","yaxis":"y","frame":null},{"x":[51],"y":[36],"text":"Chemung","mode":"markers","marker":{"color":"rgba(93,145,171,1)","size":[13.0239485027986],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(93,145,171,1)"}},"type":"scatter","name":"Chemung","textfont":{"color":"rgba(93,145,171,1)","size":13.0239485027986},"error_y":{"color":"rgba(93,145,171,1)","width":13.0239485027986},"error_x":{"color":"rgba(93,145,171,1)","width":13.0239485027986},"line":{"color":"rgba(93,145,171,1)","width":13.0239485027986},"xaxis":"x","yaxis":"y","frame":null},{"x":[45],"y":[43],"text":"Chenango","mode":"markers","marker":{"color":"rgba(118,164,164,1)","size":[11.6431653881971],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(118,164,164,1)"}},"type":"scatter","name":"Chenango","textfont":{"color":"rgba(118,164,164,1)","size":11.6431653881971},"error_y":{"color":"rgba(118,164,164,1)","width":11.6431653881971},"error_x":{"color":"rgba(118,164,164,1)","width":11.6431653881971},"line":{"color":"rgba(118,164,164,1)","width":11.6431653881971},"xaxis":"x","yaxis":"y","frame":null},{"x":[41],"y":[38],"text":"Clinton","mode":"markers","marker":{"color":"rgba(139,182,157,1)","size":[12.7826633768877],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(139,182,157,1)"}},"type":"scatter","name":"Clinton","textfont":{"color":"rgba(139,182,157,1)","size":12.7826633768877},"error_y":{"color":"rgba(139,182,157,1)","width":12.7826633768877},"error_x":{"color":"rgba(139,182,157,1)","width":12.7826633768877},"line":{"color":"rgba(139,182,157,1)","width":12.7826633768877},"xaxis":"x","yaxis":"y","frame":null},{"x":[19],"y":[11],"text":"Columbia","mode":"markers","marker":{"color":"rgba(159,202,148,1)","size":[12.0974741025912],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(159,202,148,1)"}},"type":"scatter","name":"Columbia","textfont":{"color":"rgba(159,202,148,1)","size":12.0974741025912},"error_y":{"color":"rgba(159,202,148,1)","width":12.0974741025912},"error_x":{"color":"rgba(159,202,148,1)","width":12.0974741025912},"line":{"color":"rgba(159,202,148,1)","width":12.0974741025912},"xaxis":"x","yaxis":"y","frame":null},{"x":[36],"y":[34],"text":"Cortland","mode":"markers","marker":{"color":"rgba(176,221,139,1)","size":[11.6020871535412],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(176,221,139,1)"}},"type":"scatter","name":"Cortland","textfont":{"color":"rgba(176,221,139,1)","size":11.6020871535412},"error_y":{"color":"rgba(176,221,139,1)","width":11.6020871535412},"error_x":{"color":"rgba(176,221,139,1)","width":11.6020871535412},"line":{"color":"rgba(176,221,139,1)","width":11.6020871535412},"xaxis":"x","yaxis":"y","frame":null},{"x":[39],"y":[47],"text":"Delaware","mode":"markers","marker":{"color":"rgba(159,213,123,1)","size":[11.5532684978063],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(159,213,123,1)"}},"type":"scatter","name":"Delaware","textfont":{"color":"rgba(159,213,123,1)","size":11.5532684978063},"error_y":{"color":"rgba(159,213,123,1)","width":11.5532684978063},"error_x":{"color":"rgba(159,213,123,1)","width":11.5532684978063},"line":{"color":"rgba(159,213,123,1)","width":11.5532684978063},"xaxis":"x","yaxis":"y","frame":null},{"x":[10],"y":[8],"text":"Dutchess","mode":"markers","marker":{"color":"rgba(138,201,106,1)","size":[20.5360451608568],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(138,201,106,1)"}},"type":"scatter","name":"Dutchess","textfont":{"color":"rgba(138,201,106,1)","size":20.5360451608568},"error_y":{"color":"rgba(138,201,106,1)","width":20.5360451608568},"error_x":{"color":"rgba(138,201,106,1)","width":20.5360451608568},"line":{"color":"rgba(138,201,106,1)","width":20.5360451608568},"xaxis":"x","yaxis":"y","frame":null},{"x":[26],"y":[30],"text":"Erie","mode":"markers","marker":{"color":"rgba(117,190,89,1)","size":[42.9131344745154],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(117,190,89,1)"}},"type":"scatter","name":"Erie","textfont":{"color":"rgba(117,190,89,1)","size":42.9131344745154},"error_y":{"color":"rgba(117,190,89,1)","width":42.9131344745154},"error_x":{"color":"rgba(117,190,89,1)","width":42.9131344745154},"line":{"color":"rgba(117,190,89,1)","width":42.9131344745154},"xaxis":"x","yaxis":"y","frame":null},{"x":[17],"y":[29],"text":"Essex","mode":"markers","marker":{"color":"rgba(94,179,73,1)","size":[11.2432916350649],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(94,179,73,1)"}},"type":"scatter","name":"Essex","textfont":{"color":"rgba(94,179,73,1)","size":11.2432916350649},"error_y":{"color":"rgba(94,179,73,1)","width":11.2432916350649},"error_x":{"color":"rgba(94,179,73,1)","width":11.2432916350649},"line":{"color":"rgba(94,179,73,1)","width":11.2432916350649},"xaxis":"x","yaxis":"y","frame":null},{"x":[62],"y":[57],"text":"Franklin","mode":"markers","marker":{"color":"rgba(69,167,56,1)","size":[11.6835595856415],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(69,167,56,1)"}},"type":"scatter","name":"Franklin","textfont":{"color":"rgba(69,167,56,1)","size":11.6835595856415},"error_y":{"color":"rgba(69,167,56,1)","width":11.6835595856415},"error_x":{"color":"rgba(69,167,56,1)","width":11.6835595856415},"line":{"color":"rgba(69,167,56,1)","width":11.6835595856415},"xaxis":"x","yaxis":"y","frame":null},{"x":[53],"y":[59],"text":"Fulton","mode":"markers","marker":{"color":"rgba(73,161,52,1)","size":[11.8251192864892],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(73,161,52,1)"}},"type":"scatter","name":"Fulton","textfont":{"color":"rgba(73,161,52,1)","size":11.8251192864892},"error_y":{"color":"rgba(73,161,52,1)","width":11.8251192864892},"error_x":{"color":"rgba(73,161,52,1)","width":11.8251192864892},"line":{"color":"rgba(73,161,52,1)","width":11.8251192864892},"xaxis":"x","yaxis":"y","frame":null},{"x":[42],"y":[12],"text":"Genesee","mode":"markers","marker":{"color":"rgba(117,162,73,1)","size":[11.9888561937769],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(117,162,73,1)"}},"type":"scatter","name":"Genesee","textfont":{"color":"rgba(117,162,73,1)","size":11.9888561937769},"error_y":{"color":"rgba(117,162,73,1)","width":11.9888561937769},"error_x":{"color":"rgba(117,162,73,1)","width":11.9888561937769},"line":{"color":"rgba(117,162,73,1)","width":11.9888561937769},"xaxis":"x","yaxis":"y","frame":null},{"x":[40],"y":[52],"text":"Greene","mode":"markers","marker":{"color":"rgba(152,163,93,1)","size":[11.5979469283129],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(152,163,93,1)"}},"type":"scatter","name":"Greene","textfont":{"color":"rgba(152,163,93,1)","size":11.5979469283129},"error_y":{"color":"rgba(152,163,93,1)","width":11.5979469283129},"error_x":{"color":"rgba(152,163,93,1)","width":11.5979469283129},"line":{"color":"rgba(152,163,93,1)","width":11.5979469283129},"xaxis":"x","yaxis":"y","frame":null},{"x":[24],"y":[55],"text":"Hamilton","mode":"markers","marker":{"color":"rgba(184,162,112,1)","size":[10],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(184,162,112,1)"}},"type":"scatter","name":"Hamilton","textfont":{"color":"rgba(184,162,112,1)","size":10},"error_y":{"color":"rgba(184,162,112,1)","width":10},"error_x":{"color":"rgba(184,162,112,1)","width":10},"line":{"color":"rgba(184,162,112,1)","width":10},"xaxis":"x","yaxis":"y","frame":null},{"x":[56],"y":[37],"text":"Herkimer","mode":"markers","marker":{"color":"rgba(215,159,131,1)","size":[12.148704889546],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(215,159,131,1)"}},"type":"scatter","name":"Herkimer","textfont":{"color":"rgba(215,159,131,1)","size":12.148704889546},"error_y":{"color":"rgba(215,159,131,1)","width":12.148704889546},"error_x":{"color":"rgba(215,159,131,1)","width":12.148704889546},"line":{"color":"rgba(215,159,131,1)","width":12.148704889546},"xaxis":"x","yaxis":"y","frame":null},{"x":[61],"y":[49],"text":"Jefferson","mode":"markers","marker":{"color":"rgba(246,155,150,1)","size":[14.0103661639193],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(246,155,150,1)"}},"type":"scatter","name":"Jefferson","textfont":{"color":"rgba(246,155,150,1)","size":14.0103661639193},"error_y":{"color":"rgba(246,155,150,1)","width":14.0103661639193},"error_x":{"color":"rgba(246,155,150,1)","width":14.0103661639193},"line":{"color":"rgba(246,155,150,1)","width":14.0103661639193},"xaxis":"x","yaxis":"y","frame":null},{"x":[9],"y":[56],"text":"Kings","mode":"markers","marker":{"color":"rgba(250,139,134,1)","size":[100],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(250,139,134,1)"}},"type":"scatter","name":"Kings","textfont":{"color":"rgba(250,139,134,1)","size":100},"error_y":{"color":"rgba(250,139,134,1)","width":100},"error_x":{"color":"rgba(250,139,134,1)","width":100},"line":{"color":"rgba(250,139,134,1)","width":100},"xaxis":"x","yaxis":"y","frame":null},{"x":[58],"y":[46],"text":"Lewis","mode":"markers","marker":{"color":"rgba(247,120,111,1)","size":[10.8010795787291],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(247,120,111,1)"}},"type":"scatter","name":"Lewis","textfont":{"color":"rgba(247,120,111,1)","size":10.8010795787291},"error_y":{"color":"rgba(247,120,111,1)","width":10.8010795787291},"error_x":{"color":"rgba(247,120,111,1)","width":10.8010795787291},"line":{"color":"rgba(247,120,111,1)","width":10.8010795787291},"xaxis":"x","yaxis":"y","frame":null},{"x":[29],"y":[20],"text":"Livingston","mode":"markers","marker":{"color":"rgba(243,101,89,1)","size":[12.1801706012807],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(243,101,89,1)"}},"type":"scatter","name":"Livingston","textfont":{"color":"rgba(243,101,89,1)","size":12.1801706012807},"error_y":{"color":"rgba(243,101,89,1)","width":12.1801706012807},"error_x":{"color":"rgba(243,101,89,1)","width":12.1801706012807},"line":{"color":"rgba(243,101,89,1)","width":12.1801706012807},"xaxis":"x","yaxis":"y","frame":null},{"x":[23],"y":[16],"text":"Madison","mode":"markers","marker":{"color":"rgba(238,79,67,1)","size":[12.4699503652999],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(238,79,67,1)"}},"type":"scatter","name":"Madison","textfont":{"color":"rgba(238,79,67,1)","size":12.4699503652999},"error_y":{"color":"rgba(238,79,67,1)","width":12.4699503652999},"error_x":{"color":"rgba(238,79,67,1)","width":12.4699503652999},"line":{"color":"rgba(238,79,67,1)","width":12.4699503652999},"xaxis":"x","yaxis":"y","frame":null},{"x":[20],"y":[31],"text":"Monroe","mode":"markers","marker":{"color":"rgba(232,54,45,1)","size":[36.6237363312564],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(232,54,45,1)"}},"type":"scatter","name":"Monroe","textfont":{"color":"rgba(232,54,45,1)","size":36.6237363312564},"error_y":{"color":"rgba(232,54,45,1)","width":36.6237363312564},"error_x":{"color":"rgba(232,54,45,1)","width":36.6237363312564},"line":{"color":"rgba(232,54,45,1)","width":36.6237363312564},"xaxis":"x","yaxis":"y","frame":null},{"x":[52],"y":[58],"text":"Montgomery","mode":"markers","marker":{"color":"rgba(229,43,32,1)","size":[11.6338768829024],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(229,43,32,1)"}},"type":"scatter","name":"Montgomery","textfont":{"color":"rgba(229,43,32,1)","size":11.6338768829024},"error_y":{"color":"rgba(229,43,32,1)","width":11.6338768829024},"error_x":{"color":"rgba(229,43,32,1)","width":11.6338768829024},"line":{"color":"rgba(229,43,32,1)","width":11.6338768829024},"xaxis":"x","yaxis":"y","frame":null},{"x":[1],"y":[2],"text":"Nassau","mode":"markers","marker":{"color":"rgba(236,81,46,1)","size":[58.0516700108486],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(236,81,46,1)"}},"type":"scatter","name":"Nassau","textfont":{"color":"rgba(236,81,46,1)","size":58.0516700108486},"error_y":{"color":"rgba(236,81,46,1)","width":58.0516700108486},"error_x":{"color":"rgba(236,81,46,1)","width":58.0516700108486},"line":{"color":"rgba(236,81,46,1)","width":58.0516700108486},"xaxis":"x","yaxis":"y","frame":null},{"x":[3],"y":[23],"text":"New York","mode":"markers","marker":{"color":"rgba(242,110,60,1)","size":[66.9204284713088],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(242,110,60,1)"}},"type":"scatter","name":"New York","textfont":{"color":"rgba(242,110,60,1)","size":66.9204284713088},"error_y":{"color":"rgba(242,110,60,1)","width":66.9204284713088},"error_x":{"color":"rgba(242,110,60,1)","width":66.9204284713088},"line":{"color":"rgba(242,110,60,1)","width":66.9204284713088},"xaxis":"x","yaxis":"y","frame":null},{"x":[34],"y":[44],"text":"Niagara","mode":"markers","marker":{"color":"rgba(246,136,75,1)","size":[17.6192024846152],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(246,136,75,1)"}},"type":"scatter","name":"Niagara","textfont":{"color":"rgba(246,136,75,1)","size":17.6192024846152},"error_y":{"color":"rgba(246,136,75,1)","width":17.6192024846152},"error_x":{"color":"rgba(246,136,75,1)","width":17.6192024846152},"line":{"color":"rgba(246,136,75,1)","width":17.6192024846152},"xaxis":"x","yaxis":"y","frame":null},{"x":[33],"y":[39],"text":"Oneida","mode":"markers","marker":{"color":"rgba(250,161,91,1)","size":[18.2819625387621],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(250,161,91,1)"}},"type":"scatter","name":"Oneida","textfont":{"color":"rgba(250,161,91,1)","size":18.2819625387621},"error_y":{"color":"rgba(250,161,91,1)","width":18.2819625387621},"error_x":{"color":"rgba(250,161,91,1)","width":18.2819625387621},"line":{"color":"rgba(250,161,91,1)","width":18.2819625387621},"xaxis":"x","yaxis":"y","frame":null},{"x":[22],"y":[24],"text":"Onondaga","mode":"markers","marker":{"color":"rgba(253,185,107,1)","size":[26.639745202139],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(253,185,107,1)"}},"type":"scatter","name":"Onondaga","textfont":{"color":"rgba(253,185,107,1)","size":26.639745202139},"error_y":{"color":"rgba(253,185,107,1)","width":26.639745202139},"error_x":{"color":"rgba(253,185,107,1)","width":26.639745202139},"line":{"color":"rgba(253,185,107,1)","width":26.639745202139},"xaxis":"x","yaxis":"y","frame":null},{"x":[16],"y":[5],"text":"Ontario","mode":"markers","marker":{"color":"rgba(254,183,100,1)","size":[13.711621912232],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(254,183,100,1)"}},"type":"scatter","name":"Ontario","textfont":{"color":"rgba(254,183,100,1)","size":13.711621912232},"error_y":{"color":"rgba(254,183,100,1)","width":13.711621912232},"error_x":{"color":"rgba(254,183,100,1)","width":13.711621912232},"line":{"color":"rgba(254,183,100,1)","width":13.711621912232},"xaxis":"x","yaxis":"y","frame":null},{"x":[15],"y":[22],"text":"Orange","mode":"markers","marker":{"color":"rgba(255,172,84,1)","size":[23.2478926853621],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(255,172,84,1)"}},"type":"scatter","name":"Orange","textfont":{"color":"rgba(255,172,84,1)","size":23.2478926853621},"error_y":{"color":"rgba(255,172,84,1)","width":23.2478926853621},"error_x":{"color":"rgba(255,172,84,1)","width":23.2478926853621},"line":{"color":"rgba(255,172,84,1)","width":23.2478926853621},"xaxis":"x","yaxis":"y","frame":null},{"x":[57],"y":[45],"text":"Orleans","mode":"markers","marker":{"color":"rgba(255,160,67,1)","size":[11.3697665152984],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(255,160,67,1)"}},"type":"scatter","name":"Orleans","textfont":{"color":"rgba(255,160,67,1)","size":11.3697665152984},"error_y":{"color":"rgba(255,160,67,1)","width":11.3697665152984},"error_x":{"color":"rgba(255,160,67,1)","width":11.3697665152984},"line":{"color":"rgba(255,160,67,1)","width":11.3697665152984},"xaxis":"x","yaxis":"y","frame":null},{"x":[55],"y":[61],"text":"Oswego","mode":"markers","marker":{"color":"rgba(255,149,50,1)","size":[14.2220576799378],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(255,149,50,1)"}},"type":"scatter","name":"Oswego","textfont":{"color":"rgba(255,149,50,1)","size":14.2220576799378},"error_y":{"color":"rgba(255,149,50,1)","width":14.2220576799378},"error_x":{"color":"rgba(255,149,50,1)","width":14.2220576799378},"line":{"color":"rgba(255,149,50,1)","width":14.2220576799378},"xaxis":"x","yaxis":"y","frame":null},{"x":[27],"y":[21],"text":"Otsego","mode":"markers","marker":{"color":"rgba(255,137,29,1)","size":[12.0673404633212],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(255,137,29,1)"}},"type":"scatter","name":"Otsego","textfont":{"color":"rgba(255,137,29,1)","size":12.0673404633212},"error_y":{"color":"rgba(255,137,29,1)","width":12.0673404633212},"error_x":{"color":"rgba(255,137,29,1)","width":12.0673404633212},"line":{"color":"rgba(255,137,29,1)","width":12.0673404633212},"xaxis":"x","yaxis":"y","frame":null},{"x":[5],"y":[3],"text":"Putnam","mode":"markers","marker":{"color":"rgba(254,129,19,1)","size":[13.4156498113497],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(254,129,19,1)"}},"type":"scatter","name":"Putnam","textfont":{"color":"rgba(254,129,19,1)","size":13.4156498113497},"error_y":{"color":"rgba(254,129,19,1)","width":13.4156498113497},"error_x":{"color":"rgba(254,129,19,1)","width":13.4156498113497},"line":{"color":"rgba(254,129,19,1)","width":13.4156498113497},"xaxis":"x","yaxis":"y","frame":null},{"x":[6],"y":[28],"text":"Queens","mode":"markers","marker":{"color":"rgba(250,138,67,1)","size":[90.1362554122944],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(250,138,67,1)"}},"type":"scatter","name":"Queens","textfont":{"color":"rgba(250,138,67,1)","size":90.1362554122944},"error_y":{"color":"rgba(250,138,67,1)","width":90.1362554122944},"error_x":{"color":"rgba(250,138,67,1)","width":90.1362554122944},"line":{"color":"rgba(250,138,67,1)","width":90.1362554122944},"xaxis":"x","yaxis":"y","frame":null},{"x":[31],"y":[10],"text":"Rensselaer","mode":"markers","marker":{"color":"rgba(244,147,103,1)","size":[15.565650771402],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(244,147,103,1)"}},"type":"scatter","name":"Rensselaer","textfont":{"color":"rgba(244,147,103,1)","size":15.565650771402},"error_y":{"color":"rgba(244,147,103,1)","width":15.565650771402},"error_x":{"color":"rgba(244,147,103,1)","width":15.565650771402},"line":{"color":"rgba(244,147,103,1)","width":15.565650771402},"xaxis":"x","yaxis":"y","frame":null},{"x":[11],"y":[25],"text":"Richmond","mode":"markers","marker":{"color":"rgba(236,156,136,1)","size":[26.7010925394341],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(236,156,136,1)"}},"type":"scatter","name":"Richmond","textfont":{"color":"rgba(236,156,136,1)","size":26.7010925394341},"error_y":{"color":"rgba(236,156,136,1)","width":26.7010925394341},"error_x":{"color":"rgba(236,156,136,1)","width":26.7010925394341},"line":{"color":"rgba(236,156,136,1)","width":26.7010925394341},"xaxis":"x","yaxis":"y","frame":null},{"x":[4],"y":[14],"text":"Rockland","mode":"markers","marker":{"color":"rgba(224,166,169,1)","size":[21.0472369696912],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(224,166,169,1)"}},"type":"scatter","name":"Rockland","textfont":{"color":"rgba(224,166,169,1)","size":21.0472369696912},"error_y":{"color":"rgba(224,166,169,1)","width":21.0472369696912},"error_x":{"color":"rgba(224,166,169,1)","width":21.0472369696912},"line":{"color":"rgba(224,166,169,1)","width":21.0472369696912},"xaxis":"x","yaxis":"y","frame":null},{"x":[12],"y":[1],"text":"Saratoga","mode":"markers","marker":{"color":"rgba(209,175,202,1)","size":[17.7321766304087],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(209,175,202,1)"}},"type":"scatter","name":"Saratoga","textfont":{"color":"rgba(209,175,202,1)","size":17.7321766304087},"error_y":{"color":"rgba(209,175,202,1)","width":17.7321766304087},"error_x":{"color":"rgba(209,175,202,1)","width":17.7321766304087},"line":{"color":"rgba(209,175,202,1)","width":17.7321766304087},"xaxis":"x","yaxis":"y","frame":null},{"x":[18],"y":[26],"text":"Schenectady","mode":"markers","marker":{"color":"rgba(191,164,207,1)","size":[15.3963695625042],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(191,164,207,1)"}},"type":"scatter","name":"Schenectady","textfont":{"color":"rgba(191,164,207,1)","size":15.3963695625042},"error_y":{"color":"rgba(191,164,207,1)","width":15.3963695625042},"error_x":{"color":"rgba(191,164,207,1)","width":15.3963695625042},"line":{"color":"rgba(191,164,207,1)","width":15.3963695625042},"xaxis":"x","yaxis":"y","frame":null},{"x":[32],"y":[32],"text":"Schoharie","mode":"markers","marker":{"color":"rgba(174,142,196,1)","size":[11.0049226677931],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(174,142,196,1)"}},"type":"scatter","name":"Schoharie","textfont":{"color":"rgba(174,142,196,1)","size":11.0049226677931},"error_y":{"color":"rgba(174,142,196,1)","width":11.0049226677931},"error_x":{"color":"rgba(174,142,196,1)","width":11.0049226677931},"line":{"color":"rgba(174,142,196,1)","width":11.0049226677931},"xaxis":"x","yaxis":"y","frame":null},{"x":[37],"y":[42],"text":"Schuyler","mode":"markers","marker":{"color":"rgba(157,121,186,1)","size":[10.4862784535479],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(157,121,186,1)"}},"type":"scatter","name":"Schuyler","textfont":{"color":"rgba(157,121,186,1)","size":10.4862784535479},"error_y":{"color":"rgba(157,121,186,1)","width":10.4862784535479},"error_x":{"color":"rgba(157,121,186,1)","width":10.4862784535479},"line":{"color":"rgba(157,121,186,1)","width":10.4862784535479},"xaxis":"x","yaxis":"y","frame":null},{"x":[59],"y":[40],"text":"Seneca","mode":"markers","marker":{"color":"rgba(140,100,175,1)","size":[11.0949995679765],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(140,100,175,1)"}},"type":"scatter","name":"Seneca","textfont":{"color":"rgba(140,100,175,1)","size":11.0949995679765},"error_y":{"color":"rgba(140,100,175,1)","width":11.0949995679765},"error_x":{"color":"rgba(140,100,175,1)","width":11.0949995679765},"line":{"color":"rgba(140,100,175,1)","width":11.0949995679765},"xaxis":"x","yaxis":"y","frame":null},{"x":[48],"y":[60],"text":"St. Lawrence","mode":"markers","marker":{"color":"rgba(122,80,164,1)","size":[13.8560977717188],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(122,80,164,1)"}},"type":"scatter","name":"St. Lawrence","textfont":{"color":"rgba(122,80,164,1)","size":13.8560977717188},"error_y":{"color":"rgba(122,80,164,1)","width":13.8560977717188},"error_x":{"color":"rgba(122,80,164,1)","width":13.8560977717188},"line":{"color":"rgba(122,80,164,1)","width":13.8560977717188},"xaxis":"x","yaxis":"y","frame":null},{"x":[38],"y":[33],"text":"Steuben","mode":"markers","marker":{"color":"rgba(109,64,154,1)","size":[13.389728401225],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(109,64,154,1)"}},"type":"scatter","name":"Steuben","textfont":{"color":"rgba(109,64,154,1)","size":13.389728401225},"error_y":{"color":"rgba(109,64,154,1)","width":13.389728401225},"error_x":{"color":"rgba(109,64,154,1)","width":13.389728401225},"line":{"color":"rgba(109,64,154,1)","width":13.389728401225},"xaxis":"x","yaxis":"y","frame":null},{"x":[7],"y":[6],"text":"Suffolk","mode":"markers","marker":{"color":"rgba(140,97,157,1)","size":[63.589419264408],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(140,97,157,1)"}},"type":"scatter","name":"Suffolk","textfont":{"color":"rgba(140,97,157,1)","size":63.589419264408},"error_y":{"color":"rgba(140,97,157,1)","width":63.589419264408},"error_x":{"color":"rgba(140,97,157,1)","width":63.589419264408},"line":{"color":"rgba(140,97,157,1)","width":63.589419264408},"xaxis":"x","yaxis":"y","frame":null},{"x":[49],"y":[54],"text":"Sullivan","mode":"markers","marker":{"color":"rgba(168,131,158,1)","size":[12.6177384049692],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(168,131,158,1)"}},"type":"scatter","name":"Sullivan","textfont":{"color":"rgba(168,131,158,1)","size":12.6177384049692},"error_y":{"color":"rgba(168,131,158,1)","width":12.6177384049692},"error_x":{"color":"rgba(168,131,158,1)","width":12.6177384049692},"line":{"color":"rgba(168,131,158,1)","width":12.6177384049692},"xaxis":"x","yaxis":"y","frame":null},{"x":[30],"y":[13],"text":"Tioga","mode":"markers","marker":{"color":"rgba(194,166,158,1)","size":[11.6664946573094],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(194,166,158,1)"}},"type":"scatter","name":"Tioga","textfont":{"color":"rgba(194,166,158,1)","size":11.6664946573094},"error_y":{"color":"rgba(194,166,158,1)","width":11.6664946573094},"error_x":{"color":"rgba(194,166,158,1)","width":11.6664946573094},"line":{"color":"rgba(194,166,158,1)","width":11.6664946573094},"xaxis":"x","yaxis":"y","frame":null},{"x":[8],"y":[4],"text":"Tompkins","mode":"markers","marker":{"color":"rgba(220,202,157,1)","size":[13.4823974424209],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(220,202,157,1)"}},"type":"scatter","name":"Tompkins","textfont":{"color":"rgba(220,202,157,1)","size":13.4823974424209},"error_y":{"color":"rgba(220,202,157,1)","width":13.4823974424209},"error_x":{"color":"rgba(220,202,157,1)","width":13.4823974424209},"line":{"color":"rgba(220,202,157,1)","width":13.4823974424209},"xaxis":"x","yaxis":"y","frame":null},{"x":[14],"y":[17],"text":"Ulster","mode":"markers","marker":{"color":"rgba(244,238,155,1)","size":[16.3959999423969],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(244,238,155,1)"}},"type":"scatter","name":"Ulster","textfont":{"color":"rgba(244,238,155,1)","size":16.3959999423969},"error_y":{"color":"rgba(244,238,155,1)","width":16.3959999423969},"error_x":{"color":"rgba(244,238,155,1)","width":16.3959999423969},"line":{"color":"rgba(244,238,155,1)","width":16.3959999423969},"xaxis":"x","yaxis":"y","frame":null},{"x":[25],"y":[15],"text":"Warren","mode":"markers","marker":{"color":"rgba(249,238,141,1)","size":[12.1914752162518],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(249,238,141,1)"}},"type":"scatter","name":"Warren","textfont":{"color":"rgba(249,238,141,1)","size":12.1914752162518},"error_y":{"color":"rgba(249,238,141,1)","width":12.1914752162518},"error_x":{"color":"rgba(249,238,141,1)","width":12.1914752162518},"line":{"color":"rgba(249,238,141,1)","width":12.1914752162518},"xaxis":"x","yaxis":"y","frame":null},{"x":[50],"y":[27],"text":"Washington","mode":"markers","marker":{"color":"rgba(236,208,120,1)","size":[12.101794337612],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(236,208,120,1)"}},"type":"scatter","name":"Washington","textfont":{"color":"rgba(236,208,120,1)","size":12.101794337612},"error_y":{"color":"rgba(236,208,120,1)","width":12.101794337612},"error_x":{"color":"rgba(236,208,120,1)","width":12.101794337612},"line":{"color":"rgba(236,208,120,1)","width":12.101794337612},"xaxis":"x","yaxis":"y","frame":null},{"x":[43],"y":[19],"text":"Wayne","mode":"markers","marker":{"color":"rgba(223,178,99,1)","size":[13.2018701817379],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(223,178,99,1)"}},"type":"scatter","name":"Wayne","textfont":{"color":"rgba(223,178,99,1)","size":13.2018701817379},"error_y":{"color":"rgba(223,178,99,1)","width":13.2018701817379},"error_x":{"color":"rgba(223,178,99,1)","width":13.2018701817379},"line":{"color":"rgba(223,178,99,1)","width":13.2018701817379},"xaxis":"x","yaxis":"y","frame":null},{"x":[2],"y":[9],"text":"Westchester","mode":"markers","marker":{"color":"rgba(208,148,78,1)","size":[43.9958213726827],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(208,148,78,1)"}},"type":"scatter","name":"Westchester","textfont":{"color":"rgba(208,148,78,1)","size":43.9958213726827},"error_y":{"color":"rgba(208,148,78,1)","width":43.9958213726827},"error_x":{"color":"rgba(208,148,78,1)","width":43.9958213726827},"line":{"color":"rgba(208,148,78,1)","width":43.9958213726827},"xaxis":"x","yaxis":"y","frame":null},{"x":[44],"y":[18],"text":"Wyoming","mode":"markers","marker":{"color":"rgba(193,119,59,1)","size":[11.3435570895057],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(193,119,59,1)"}},"type":"scatter","name":"Wyoming","textfont":{"color":"rgba(193,119,59,1)","size":11.3435570895057},"error_y":{"color":"rgba(193,119,59,1)","width":11.3435570895057},"error_x":{"color":"rgba(193,119,59,1)","width":11.3435570895057},"line":{"color":"rgba(193,119,59,1)","width":11.3435570895057},"xaxis":"x","yaxis":"y","frame":null},{"x":[21],"y":[35],"text":"Yates","mode":"markers","marker":{"color":"rgba(177,89,40,1)","size":[10.7384721728862],"sizemode":"diameter","opacity":0.5,"line":{"color":"rgba(177,89,40,1)"}},"type":"scatter","name":"Yates","textfont":{"color":"rgba(177,89,40,1)","size":10.7384721728862},"error_y":{"color":"rgba(177,89,40,1)","width":10.7384721728862},"error_x":{"color":"rgba(177,89,40,1)","width":10.7384721728862},"line":{"color":"rgba(177,89,40,1)","width":10.7384721728862},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
<pre class="r"><code>write.csv(total,&quot;./data/eda_bubble.csv&quot;)</code></pre>
<p>From the plot we can see that New York, Queens and Kings have the
highest socio economic score, but have the lowest health factors ranks.
The size of the bubble signifies total population of the county. Nassau,
Suffolk, Westcher have low health and socio-ecnomic scores.</p>
<p>Below is a chloropleth map to good understanding on the above in a
spatial context,:</p>
<pre class="r"><code>#library(sf)
#total = st_as_sf(total)
p = list()
p[[1]] = total %&gt;%
  ggplot() +
  geom_sf(aes(fill = medage, geometry = geometry)) + 
  scale_fill_viridis_c(option = &quot;viridis&quot;, name = &quot;Median Age&quot;) +
  ggtitle(&quot;Median Age Per County in New York State&quot;)


p[[2]] = total %&gt;%
  ggplot() +
  geom_sf(aes(fill = health_beh_r, geometry = geometry)) + 
  scale_fill_viridis_c(option = &quot;viridis&quot;,name = &quot;Health Factor Score&quot;) +
  ggtitle(&quot;Heath Rank Per County in New York State&quot;)

grid.arrange(p[[1]], p[[2]], nrow = 1)</code></pre>
<p><img src="Final-Report-Main_files/figure-html/unnamed-chunk-10-1.png" width="90%" /></p>
<p>On the left we can see a chloropleth mao of medage per county in new
york on the right is a chloropleth map of health factor rank per
county.</p>
<p>Before testing association between county health factors (HR) and
COVID, we wanted to see rather there are any observable patterns between
COVID cases &amp; HR, COVID vaccination &amp; HR, and COVID deaths &amp;
HR.</p>
<pre class="r"><code>p1 = ggplot(data=eda1, aes(x=rank_var, y=n_deaths, fill=quartile)) +
  geom_bar(stat=&quot;identity&quot;, position=position_dodge())+
  scale_fill_brewer(palette=&quot;Reds&quot;) + 
  theme_minimal() +
  labs(title=&quot;Number of COVID Deaths and County Health Factors by Quartile&quot;,
        x =&quot;County Health Factors&quot;, y = &quot;Number of Deaths&quot;)

p2 = ggplot(data=eda1, aes(x=rank_var, y=n_cases, fill=quartile)) +
  geom_bar(stat=&quot;identity&quot;, position=position_dodge())+
  scale_fill_brewer(palette=&quot;Oranges&quot;) + 
  theme_minimal() +
  labs(title=&quot;Number of COVID Cases and County Health Factors by Quartile&quot;,
        x =&quot;County Health Factors&quot;, y = &quot;Number of Cases&quot;)

p3 = ggplot(data=eda1, aes(x=rank_var, y=vax_dose1, fill=quartile)) +
  geom_bar(stat=&quot;identity&quot;, position=position_dodge())+
  scale_fill_brewer(palette=&quot;Greens&quot;) + 
  theme_minimal() +
  labs(title=&quot;Covid Vaccination (Dose 1) and County Health Factors by Quartile&quot;,
        x =&quot;County Health Factors&quot;, y = &quot;Number of People Vaccinated&quot;)

grid.arrange(p1, p2, p3, ncol = 1)</code></pre>
<p><img src="Final-Report-Main_files/figure-html/unnamed-chunk-11-1.png" width="90%" /></p>
</div>
<div id="statistical-analysis" class="section level2">
<h2>Statistical Analysis</h2>
<p>Note: Though we initially planned to adjust for racial diversity in
our model, the variable was removed because racial diversity index did
not vary much among counties. Also, tpop (total population) was replaced
with pop_d (population density) as it was shown that COVID-19 incidence
is strongly correlated with population density (Iderus, 2022). For the
models, only data from 2021 or 2022 were used as there is no information
on vaccination for 2020.</p>
<p style="color: red">
<strong><em>Question 1: Are county health factors associated with
COVID-19 risk?</em></strong>
</p>
<p>Health factors–health behaviors, clinical care, physical environment,
and socioeconomic factors–are community conditions that can be modified
and improved through public health interventions or health policies.
Therefore, we were interested in seeing which factor(s) is significantly
associated with the number of COVID-19 cases, deaths, and vaccination.
To do so, we ran multiple linear regression test.</p>
<div id="nys-county-health-factors-and-covid-cases"
class="section level3">
<h3>NYS County Health Factors and Covid Cases</h3>
<p><span class="math inline">\(N_{Covid\_Cases} \sim \beta_{0} +
\beta_{1} Health\_Behavior + \beta_{2} Clinical\_Care + \beta_{3}
Physical\_Environment + \beta_{4} SES\_Factors + \beta_{5} Median\_Age +
\beta_{6} Population\_Density + \epsilon\)</span></p>
<pre class="r"><code>m1 = comb %&gt;% 
  filter(year == &#39;2021&#39;) %&gt;% 
  lm(n_cases ~ health_beh_r + clinical_care_r + env_r + ses_r + medage + 
       pop_d, data = .)

m1 %&gt;% 
  broom::tidy() %&gt;%
  select(term, estimate, p.value) %&gt;% 
  kbl(
    caption = &quot;Health Factor Ranking &amp; COVID Outbreak&quot;
    , col.names = c(&quot;Predictor&quot;, &quot;Estimate&quot;, &quot;p-value&quot;)
    , digits = 3) %&gt;% 
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;condensed&quot;), 
                full_width = FALSE)</code></pre>
<table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Health Factor Ranking &amp; COVID Outbreak
</caption>
<thead>
<tr>
<th style="text-align:left;">
Predictor
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
p-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
190698.492
</td>
<td style="text-align:right;">
0.025
</td>
</tr>
<tr>
<td style="text-align:left;">
health_beh_r
</td>
<td style="text-align:right;">
-2399.531
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
clinical_care_r
</td>
<td style="text-align:right;">
844.353
</td>
<td style="text-align:right;">
0.056
</td>
</tr>
<tr>
<td style="text-align:left;">
env_r
</td>
<td style="text-align:right;">
304.032
</td>
<td style="text-align:right;">
0.409
</td>
</tr>
<tr>
<td style="text-align:left;">
ses_r
</td>
<td style="text-align:right;">
798.434
</td>
<td style="text-align:right;">
0.127
</td>
</tr>
<tr>
<td style="text-align:left;">
medage
</td>
<td style="text-align:right;">
-3583.385
</td>
<td style="text-align:right;">
0.074
</td>
</tr>
<tr>
<td style="text-align:left;">
pop_d
</td>
<td style="text-align:right;">
3.042
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
</tbody>
</table>
<p>After adjusting for median age and population density, only health
behaviors ranking was shown to be significantly associated with the
number of COVID-19 cases (p &lt; .05). The estimate for health behavior
ranking was -2399.531, indicating that counties with higher health
behavior ranking had lower number of COVID cases.</p>
<p><br>Health behaviors score is based on community residents’ tobacco
use, diet &amp; exercise, alcohol &amp; drug use, and sexual activity
(i.e., number of STI, teen pregnancy). These subfactors are often viewed
as drivers of health inequity. Rate of teen pregnancy is higher in
majority-minority district; alcohol and drug abuse are more common among
minorities; and residential segregation limits minorities access to
healthy food. Therefore, the results warrant further exploration of
interaction between the health behaviors ranking, its subfactors, and
race/ethnicity.</p>
<p>To test the validity of our results, we checked regression
assumptions.</p>
<pre class="r"><code>par(mfrow = c(2,2))
plot(m1)</code></pre>
<p><img src="Final-Report-Main_files/figure-html/m1_check-1.png" width="90%" /></p>
<p>Test for linearity (residual vs. fitted values) does not show strong
pattern; however, the points are not perfectly, randomly scattered
around residual = 0. Test for influential observations (residual
vs. leverage) shows that there is one influential point (#31), which
should be tested to see whether it should be removed or kept. Test for
homoscedasticity (scale-location) indicates potential
heteroscedasticity. Lastly, test for normality of residuals (normal Q-Q
plot) confirms that there is no extreme skewness in our data with
majority of the points falling along the line. Some deviations at the
lowest and highest quantiles suggest that random fluctuation may be seen
at extreme ends. Combined, the plots indicate that our model, though
sufficient, can be improved (i.e., add interaction terms, adjust for
more variables).</p>
</div>
<div id="nys-county-health-factors-and-covid-fatalities"
class="section level3">
<h3>NYS County Health Factors and Covid Fatalities</h3>
<p><span class="math inline">\(N_{Deaths} \sim \beta_{0} + \beta_{1}
Health\_Behavior + \beta_{2} Clinical\_Care + \beta_{3}
Physical\_Environment + \beta_{4} SES\_Factors + \beta_{5}
Population\_Density + \beta_{6} Median\_Age + \epsilon\)</span></p>
<pre class="r"><code>m2 = comb %&gt;% 
  filter(year == &#39;2021&#39;) %&gt;% 
  lm(n_deaths ~ health_beh_r + clinical_care_r + env_r + ses_r + pop_d + 
       medage, data = .)

m2 %&gt;% 
broom::tidy() %&gt;%
  select(term, estimate, p.value) %&gt;% 
  kbl(
    caption = &quot;Health Factor Ranking &amp; COVID Deaths&quot;
    , col.names = c(&quot;Predictor&quot;, &quot;Estimate&quot;, &quot;p-value&quot;)
    , digits = 3) %&gt;% 
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;condensed&quot;), full_width = FALSE)</code></pre>
<table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Health Factor Ranking &amp; COVID Deaths
</caption>
<thead>
<tr>
<th style="text-align:left;">
Predictor
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
p-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
3346.642
</td>
<td style="text-align:right;">
0.037
</td>
</tr>
<tr>
<td style="text-align:left;">
health_beh_r
</td>
<td style="text-align:right;">
-43.684
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
clinical_care_r
</td>
<td style="text-align:right;">
12.660
</td>
<td style="text-align:right;">
0.127
</td>
</tr>
<tr>
<td style="text-align:left;">
env_r
</td>
<td style="text-align:right;">
6.440
</td>
<td style="text-align:right;">
0.355
</td>
</tr>
<tr>
<td style="text-align:left;">
ses_r
</td>
<td style="text-align:right;">
16.106
</td>
<td style="text-align:right;">
0.104
</td>
</tr>
<tr>
<td style="text-align:left;">
pop_d
</td>
<td style="text-align:right;">
0.075
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
medage
</td>
<td style="text-align:right;">
-62.656
</td>
<td style="text-align:right;">
0.098
</td>
</tr>
</tbody>
</table>
<p>As seen with model 1, model 2 shows that only health behaviors
ranking is significantly associated with the number of COVID deaths in
each county (p &lt; .05). The estimate is -43.684, meaning that counties
with better health behaviors ranking had less number of COVID deaths.
The finding suggests that public health professionals should aim to
mitigate disparities in COVID-19 by first starting short-term
community-based interventions that encourage residents to build
healthier lifestyles and make healthier life choices.</p>
<pre class="r"><code>par(mfrow = c(2,2))
plot(m2)</code></pre>
<p><img src="Final-Report-Main_files/figure-html/m2_check-1.png" width="90%" /></p>
<p>Results of regression assumption tests are also similar to that of
model 1’s, indicating that there is more to be explored in the
association between health factor and COVID-19 fatalities. Once again,
point 31 shows up as an outlier that needs to be tested further.</p>
</div>
<div id="nys-county-health-factors-and-vaccination-dose-1"
class="section level3">
<h3>NYS County Health Factors and Vaccination (Dose 1)</h3>
<p><span class="math inline">\(Vaccine\_Dose1 \sim \beta_{0} + \beta_{1}
Health\_Behavior + \beta_{2} Clinical\_Care + \beta_{3} SES\_Factors +
\beta_{4} Physical\_Environment + \beta_{5} Population\_Density +
\epsilon\)</span></p>
<pre class="r"><code>m3 = comb %&gt;% 
  filter(year == &#39;2022&#39;) %&gt;% 
  lm(vax_dose1 ~ health_beh_r + clinical_care_r + ses_r + env_r + pop_d, data = .,)

m3 %&gt;% 
  broom::tidy() %&gt;%
  select(term, estimate, p.value) %&gt;% 
  kbl(
    caption = &quot;Health Factor Ranking &amp; COVID Vaccination (Dose # 1)&quot;
    , col.names = c(&quot;Predictor&quot;, &quot;Estimate&quot;, &quot;p-value&quot;)
    , digits = 3) %&gt;% 
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;condensed&quot;), full_width = FALSE)</code></pre>
<table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Health Factor Ranking &amp; COVID Vaccination (Dose # 1)
</caption>
<thead>
<tr>
<th style="text-align:left;">
Predictor
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
p-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
203186.314
</td>
<td style="text-align:right;">
0.078
</td>
</tr>
<tr>
<td style="text-align:left;">
health_beh_r
</td>
<td style="text-align:right;">
-11691.771
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
clinical_care_r
</td>
<td style="text-align:right;">
2578.554
</td>
<td style="text-align:right;">
0.316
</td>
</tr>
<tr>
<td style="text-align:left;">
ses_r
</td>
<td style="text-align:right;">
4712.004
</td>
<td style="text-align:right;">
0.095
</td>
</tr>
<tr>
<td style="text-align:left;">
env_r
</td>
<td style="text-align:right;">
4119.234
</td>
<td style="text-align:right;">
0.059
</td>
</tr>
<tr>
<td style="text-align:left;">
pop_d
</td>
<td style="text-align:right;">
23.036
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
</tbody>
</table>
<p>In this model, we did not adjust for median age since COVID-19
vaccination rate did not vary significantly for 18+ by 2022. As seen in
models 1 and 2, model 3 once again showed that county’s health behaviors
rank is significantly associated with the number of individuals who
received the first dose of the vaccine (p &lt; .05). Once again, the
estimate is negative (-11691). This implies that individuals who take
care of their health holistically may be more likely to choose to
receive the vaccine.</p>
<pre class="r"><code>par(mfrow = c(2,2))
plot(m3)</code></pre>
<p><img src="Final-Report-Main_files/figure-html/m3_check-1.png" width="90%" /></p>
<p>Regression assumption tests, once again, show room for improvement in
our model and the need to test the outliers, especially point #31.</p>
<p style="color: red">
<strong><em>Question 2: Can race/ethnicity or socioeconomic status in
counties help determine COVID-19 severity?</em></strong>
</p>
</div>
<div id="socioeconomic-factors-raceethnicity-and-vaccination-rate"
class="section level3">
<h3>Socioeconomic Factors, Race/Ethnicity and Vaccination Rate</h3>
<p><span class="math inline">\(Vaccination \sim \beta_{0} + \beta_{1}
Segregation\_Score + \beta_{2} Median\_Income + \beta_{3}
Percent\_Minority + \beta_{4} Population\_Density +
\epsilon\)</span></p>
<pre><code>## 
## Call:
## glm(formula = vax_maj ~ segregation_score + median_income + p_minority + 
##     pop_d, data = .)
## 
## Deviance Residuals: 
##      Min        1Q    Median        3Q       Max  
## -0.70450  -0.09186  -0.02932   0.04899   0.85132  
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       -7.880e-01  1.943e-01  -4.055 0.000154 ***
## segregation_score  7.594e-04  3.438e-03   0.221 0.825983    
## median_income      1.261e-05  2.470e-06   5.104 3.98e-06 ***
## p_minority         8.372e-03  3.364e-03   2.488 0.015776 *  
## pop_d              8.520e-06  4.152e-06   2.052 0.044769 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for gaussian family taken to be 0.07193672)
## 
##     Null deviance: 10.2742  on 61  degrees of freedom
## Residual deviance:  4.1004  on 57  degrees of freedom
## AIC: 19.553
## 
## Number of Fisher Scoring iterations: 2</code></pre>
<table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
SES Factors &amp; COVID Vaccination
</caption>
<thead>
<tr>
<th style="text-align:left;">
Predictor
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
OR
</th>
<th style="text-align:right;">
OR CI, low
</th>
<th style="text-align:right;">
OR CI, high
</th>
<th style="text-align:right;">
p-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
-0.788
</td>
<td style="text-align:right;">
0.455
</td>
<td style="text-align:right;">
0.311
</td>
<td style="text-align:right;">
0.666
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
segregation_score
</td>
<td style="text-align:right;">
0.001
</td>
<td style="text-align:right;">
1.001
</td>
<td style="text-align:right;">
0.994
</td>
<td style="text-align:right;">
1.008
</td>
<td style="text-align:right;">
0.826
</td>
</tr>
<tr>
<td style="text-align:left;">
median_income
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
p_minority
</td>
<td style="text-align:right;">
0.008
</td>
<td style="text-align:right;">
1.008
</td>
<td style="text-align:right;">
1.002
</td>
<td style="text-align:right;">
1.015
</td>
<td style="text-align:right;">
0.016
</td>
</tr>
<tr>
<td style="text-align:left;">
pop_d
</td>
<td style="text-align:right;">
0.000
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
1.000
</td>
<td style="text-align:right;">
0.045
</td>
</tr>
</tbody>
</table>
<p>Based on the the results, median_income and p_minority are
significantly associated with higher chance of majority of the county’s
resident being vaccinated (p &lt; .05). However, despite being
statistically significant, because the estimates aare ~0 and ORs are
also ~1, the significance is not meaningful. Therefore, though SES
factors may contribute, their effects, perhaps, are not as pronounced
unless combined with geographical proximity to locations with COVID-19
outbreak. The findings in model 3 could also have happened because COVID
vaccine was available at locations such pharmacies (CVS, Walgreen, etc.)
and community health centers, removing the barrier to healthcare access
and increasing equal access to the vaccine.</p>
<p>Upon checking our model,</p>
<pre class="r"><code>par(mfrow = c(2,2))
plot(m4)</code></pre>
<p><img src="Final-Report-Main_files/figure-html/m4_check-1.png" width="90%" /></p>
<p>we did see the need to adjust our model; however, with the lack of
2022 data and demographics information, further analysis and
modifications could not be completed. The residual vs. fitted plot did
not give us much information as the outcome variable of our model is
binary. The normal Q-Q plot showed that our data is not skewed, though
there are deviations at extreme quantiles. Furthermore, there appears to
be potential heteroscedasticity per scale-location plot and one outlier
(point #3 falls outside Cook’s distance).</p>
</div>
<div id="socioeconomic-factors-raceethnicity-and-covid-fatalities"
class="section level3">
<h3>Socioeconomic factors, Race/Ethnicity and COVID Fatalities</h3>
<p><span class="math inline">\(N_{Deaths} \sim \beta_{0} + \beta_{1}
Segregation\_Score + \beta_{2} Percent\_Minority + \beta_{3}
Median\_Income + \beta_{4} Median\_Age + \beta_{5} Population\_Density +
\epsilon\)</span></p>
<pre class="r"><code>m5 = comb %&gt;% 
  filter(year == &#39;2021&#39;) %&gt;% 
  lm(n_deaths ~ segregation_score + p_minority + median_income + medage + pop_d,
     data = .)

m5 %&gt;% 
  broom::tidy() %&gt;%
  select(term, estimate, p.value) %&gt;% 
  kbl(
    caption = &quot;SES Factors &amp; COVID Deaths&quot;
    , col.names = c(&quot;Predictor&quot;, &quot;Estimate&quot;, &quot;p-value&quot;)
    , digits = 3) %&gt;% 
  kable_styling(bootstrap_options = c(&quot;striped&quot;, &quot;condensed&quot;), full_width = FALSE)</code></pre>
<table class="table table-striped table-condensed" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
SES Factors &amp; COVID Deaths
</caption>
<thead>
<tr>
<th style="text-align:left;">
Predictor
</th>
<th style="text-align:right;">
Estimate
</th>
<th style="text-align:right;">
p-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
-2152.475
</td>
<td style="text-align:right;">
0.212
</td>
</tr>
<tr>
<td style="text-align:left;">
segregation_score
</td>
<td style="text-align:right;">
17.565
</td>
<td style="text-align:right;">
0.050
</td>
</tr>
<tr>
<td style="text-align:left;">
p_minority
</td>
<td style="text-align:right;">
44.441
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
median_income
</td>
<td style="text-align:right;">
0.016
</td>
<td style="text-align:right;">
0.022
</td>
</tr>
<tr>
<td style="text-align:left;">
medage
</td>
<td style="text-align:right;">
10.912
</td>
<td style="text-align:right;">
0.784
</td>
</tr>
<tr>
<td style="text-align:left;">
pop_d
</td>
<td style="text-align:right;">
0.064
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
</tbody>
</table>
<p>This model shows the number of COVID-19 fatalities in each county is
significantly associated with segregation score, % minority (black and
Hispanic), and median income (p &lt;= .05) after adjusting for
population density. Segregation score had a positive estimate of 17.565,
indicating that residential segregation of white vs. non-white could
have played a role in exacerbating the COVID-19 disparity. Positive
estimate for % minority (estimate = 44.441) reinforces this notion. As
for median income, because the estimate is ~0, despite statistical
significance, meaningful interepration is lacking. These findings
demonstrate that unlike vaccination, racial/ethnic minorities,
specifically Hispanic and Black, had a higher risk of dying from COVID
compared to White/Asian.</p>
<pre class="r"><code>par(mfrow = c(2,2))
plot(m5)</code></pre>
<p><img src="Final-Report-Main_files/figure-html/m5_check-1.png" width="90%" /></p>
<p>For regression test plots, the conclusions are very similar to that
of model 4’s. The residual vs. fitted plot does not show clear patterns;
however, the points are also not equally, randomly distributed along
residual = 0 line. The Q-Q plot confirms our data is normally
distributed with no extreme skewness. Scale-location shows possibility
of homoscedasticity violation and residual vs. leverage, shows that
points #3 and #31 are influential observations; combined with model 1 to
model 4, this indicates that points 3 and 31 should be identified and
tested to determine whether they should be kept or removed from our
dataset.</p>
</div>
<div id="model-6" class="section level3">
<h3>Model 6</h3>
<p style="color: red">
<strong><em>Question 3: Are county percentages of smokers, obesity,
physical inactivity, and excessive alcohol drinking associated with
receiving at least the first dose of any COVID-19 vaccine?</em></strong>
</p>
<p>The health behaviors ranking was a significant predictor of having
increases in the amount of people who have had at least their first dose
of the COVID-19 vaccine. The health behaviors ranking encompasses a
broad array of sub-variables. Of particular interest to explore are well
known factors such as smoking, obesity, exercise, and alcohol
consumption. All these factors are well established predictors of many
existing health conditions such as CVD, diabetes, cancer, etc.
Therefore, we are now interested in seeing if these factor’s affect the
attainment of getting at least the first dose of the COVID vaccine.</p>
<p>Note: Again, since the distribution of vaccines for COVID began in
2021 and the complete data for 2022 is not yet available, we will focus
our model on data from the 2021 year.</p>
<p><span class="math inline">\(vax_dose_1 = \beta_{0} + \beta_{1}
percent\_smokers + \beta_{2} percent\_obese + \beta_{3}
percent\_physically\_inactive + \beta_{4}
percent\_excessive\_drinking\)</span></p>
<pre class="r"><code>subm1 =
  new_comb %&gt;%
  filter(year == &#39;2021&#39;) %&gt;%
  lm(vax_dose1 ~ percent_smokers + percent_obese + percent_physically_inactive + percent_excessive_drinking, data = .)

subm1 %&gt;% 
  broom::tidy() %&gt;% 
  select(term, estimate, p.value) %&gt;% 
  knitr::kable(digits = 3) </code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
2292873.03
</td>
<td style="text-align:right;">
0.007
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_smokers
</td>
<td style="text-align:right;">
-76643.87
</td>
<td style="text-align:right;">
0.009
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_obese
</td>
<td style="text-align:right;">
-36671.94
</td>
<td style="text-align:right;">
0.028
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_physically_inactive
</td>
<td style="text-align:right;">
49265.75
</td>
<td style="text-align:right;">
0.015
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_excessive_drinking
</td>
<td style="text-align:right;">
-26836.39
</td>
<td style="text-align:right;">
0.410
</td>
</tr>
</tbody>
</table>
<p>From the results, we can see that every predictor has a significant
p-value of less than 0.05, except for the variable
<code>percent_excessive_drinking</code>. The negative estimates for
smokers and obesity suggests that for each percent increase in the
adults with obesity or smoking, the amount of people in that county who
have at least the first dose of a COVID vaccine decreases. However, for
the variables for physical inactivity, the estimate is positive. The
estimates in this model are not completely reliable as we have
previously established that our COVID outcomes (cases, deaths, and first
dose of vaccine) is dependent on geospacial factors. Our data is by
county and not individuals which have an influence on the results.
Further analysis is necessary on the group level to get more precise
estimates. However, from these results, public health professional can
focus resources and interventions on smokers and those with obesity to
increase vaccination numbers.</p>
</div>
<div id="model-7" class="section level3">
<h3>Model 7</h3>
<p style="color: red">
<strong><em>Question 4: Adjusting for median age, is unemployment
associated with receiving at least the first dose of any COVID-19
vaccine?</em></strong>
</p>
<p>Unemployment can be a predictor for a variety of outcomes. Often
times, people cannot prioritize their health as a result of a lack of
money due. It is worth seeing if unemployment is associated with getting
the first dose of a COVID vaccine.</p>
<p><span class="math inline">\(vax_dose_1 = \beta_{0} + \beta_{1} medage
+ \beta_{2} percent\_unemployed\)</span></p>
<pre class="r"><code>subm2 =
  new_comb %&gt;%
  filter(year == &#39;2021&#39;) %&gt;%
  lm(vax_dose1 ~ medage + percent_unemployed, data = .)

subm2 %&gt;% 
  broom::tidy() %&gt;% 
  select(term, estimate, p.value) %&gt;% 
  knitr::kable(digits = 3) </code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
p.value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
(Intercept)
</td>
<td style="text-align:right;">
3142966.29
</td>
<td style="text-align:right;">
0.000
</td>
</tr>
<tr>
<td style="text-align:left;">
medage
</td>
<td style="text-align:right;">
-50421.47
</td>
<td style="text-align:right;">
0.002
</td>
</tr>
<tr>
<td style="text-align:left;">
percent_unemployed
</td>
<td style="text-align:right;">
-200310.36
</td>
<td style="text-align:right;">
0.014
</td>
</tr>
</tbody>
</table>
<p>From the results, we can see that after adjusting for median age, the
p-value for unemployment is significant. As stated before, since the
outcomes are geospacially correlated, the estimate values are not
accurate. But the direction states that for each percent increase in
unemployment in a county, the number of people who have had at least one
dose of a COVID vaccine decreases. This information can help public
health professionals direct resources and attention towards people who
are currently unemployed. People who are unemployment may not have
gotten the vaccine because they think that it may be an extra expense
that they cannot afford to have. This is where it is important to reach
out to this group to make sure they are informed that the vaccine is
free for everyone and encourage them to get vaccinated.</p>
</div>
</div>
<div id="spatial-analysis" class="section level2">
<h2>Spatial Analysis</h2>
<pre class="r"><code>ny_covid = read.csv(&#39;data/covid_testing.csv&#39;)  %&gt;%
  janitor::clean_names()

###############################
ny_covid$test_date = lubridate::mdy(ny_covid$test_date)
##############################
total &lt;- merge(ny_covid,NY_df,by=&quot;county&quot;)</code></pre>
<pre class="r"><code>mon = seq(as.Date(&quot;2021-01-01&quot;), as.Date(&quot;2022-01-01&quot;), by = &quot;3 months&quot;)
df_list = list()
# loop version 2
for (i in 1:4) {
  sub_df = total[total$test_date &gt;= mon[[i]] &amp; total$test_date &lt;= mon[[i+1]], ]
  group_df =  sub_df %&gt;% group_by(county)  %&gt;%
    summarise(total_covid = sum(new_positives),
              pop = sum(tpop)/as.numeric(mon[i+1]-mon[i]))
  df = dplyr :: left_join(group_df, NY_df, by = &#39;county&#39;)
  df_list[[i]] = df
}


p &lt;- list()
for(i in 1:4){
  p[[i]] &lt;- df_list[[i]] %&gt;%
    ggplot() +geom_sf(aes(fill = total_covid/pop, geometry = geometry)) + 
    scale_fill_viridis_c(option = &quot;magma&quot;, name = &quot;Incidence&quot;,
                         direction = -1) +
    ggtitle(paste(mon[[i]],&quot;to&quot;, mon[[i+1]]))
}

do.call(grid.arrange,p)</code></pre>
<p><img src="Final-Report-Main_files/figure-html/unnamed-chunk-20-1.png" width="90%" /></p>
<p>The above 4 chloroplast maps are a quarterly summary of the positive
covid cases at a <strong>log10</strong> scale. Although there are minor
difference between some counties from quarter to quarter, the relative
standing of the county,</p>
</div>
<div id="autoregression" class="section level2">
<h2>Autoregression</h2>
<pre class="r"><code>ny_covid = read.csv(&#39;data/covid_testing.csv&#39;)  %&gt;%
  janitor::clean_names()

######################################################
ny_covid$test_date = lubridate::mdy(ny_covid$test_date)
sub_df = ny_covid[ny_covid$county == &#39;New York City&#39;, ]
sub_df&lt;- sub_df[seq(dim(sub_df)[1],1),]

ggplot(sub_df, aes(x=test_date, y=new_positives)) + 
  geom_point(alpha = 10/100, colour = &quot;red&quot;) + 
  scale_x_date(date_labels = &quot;%m-%Y&quot;) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(title = &quot;New positive covid cases per month in NYC&quot;)</code></pre>
<p><img src="Final-Report-Main_files/figure-html/unnamed-chunk-21-1.png" width="90%" />
The above plot is a scatter plot of the daily positive cases in New York
City from March 2020 up-till now. We can see the wave like trend,
especially from hill shaped curves at the start of the 2020, start of
2021, start of 2022 when it peaked around mid 2022. This implies the
existence of auto regressive behavior which we were interested to
investigate. To better understand the auto-regressive trend we built a
Autocorrelation Function (ACF) plot and Partial Autocorrelation Function
(PACF) plot. The ACF and PACF plots are used to figure out the order of
AR, MA, and ARMA models. Autocorrelation is the correlation between a
time series with a lagged version. The partial autocorrelation at lag k
is the autocorrelation between X_t_t and X_(t-k) that is not accounted
for by lags 1 through 𝑘−1.</p>
<pre class="r"><code>library(forecast)</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;quantmod&#39;:
##   method            from
##   as.zoo.data.frame zoo</code></pre>
<pre><code>## 
## Attaching package: &#39;forecast&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:nlme&#39;:
## 
##     getResponse</code></pre>
<pre class="r"><code>library(ggplot2)

conf.level &lt;- 0.95
ciline &lt;- qnorm((1 - conf.level)/2)/sqrt(length(sub_df$new_positives))

############# ACF ####################
bacf &lt;- acf(sub_df$new_positives, plot = FALSE)
bacfdf &lt;- with(bacf, data.frame(lag, acf))

p1 &lt;- ggplot(data=bacfdf, mapping=aes(x=lag, y=acf)) +
       geom_bar(stat = &quot;identity&quot;, position = &quot;identity&quot;) +
  ggtitle(&quot;Autocorrelation Plot&quot;)


########### PACF ###################
bacf &lt;- pacf(sub_df$new_positives, plot = FALSE)
bacfdf &lt;- with(bacf, data.frame(lag, acf))


p2 &lt;- ggplot(data=bacfdf, mapping=aes(x=lag, y=acf)) +
  geom_bar(stat = &quot;identity&quot;, position = &quot;identity&quot;,fill=&quot;lightblue&quot;)  +
  ggtitle(&quot;Partial Autocorrelation Plot&quot;)

grid.arrange(p1,p2)</code></pre>
<p><img src="Final-Report-Main_files/figure-html/unnamed-chunk-22-1.png" width="90%" />
Both the ACF and PACF start with a lag of 0, which is the correlation of
the time series with itself and therefore results in a correlation of 1.
However after a lag of 1, ACF gives us values of auto-correlation of any
series with its lagged values whereas PACF finds correlation of the
residuals that remains after removing the effects which are already
explained by the earlier lag(s). Thus PACF might be a better indicator
of how many lag terms to keep. In our case we decided to move with the 8
lag terms since they seem to have significant partial autcorrelation
with value at lag = 0 (present value).</p>
<pre class="r"><code>reg1 = arima(sub_df$new_positives, order = c(8,0,0))
summary(reg1)</code></pre>
<pre><code>## 
## Call:
## arima(x = sub_df$new_positives, order = c(8, 0, 0))
## 
## Coefficients:
##          ar1      ar2     ar3     ar4      ar5     ar6     ar7      ar8
##       1.0562  -0.2312  0.0948  0.0779  -0.1035  0.1343  0.3918  -0.4517
## s.e.  0.0283   0.0421  0.0425  0.0425   0.0424  0.0424  0.0420   0.0282
##       intercept
##        2924.354
## s.e.   1117.515
## 
## sigma^2 estimated as 1259656:  log likelihood = -8351.82,  aic = 16723.63
## 
## Training set error measures:
##                     ME     RMSE      MAE  MPE MAPE      MASE       ACF1
## Training set 0.7579743 1122.344 505.0917 -Inf  Inf 0.9324851 -0.1255802</code></pre>
<p>The coefficients for an AR(8) model represent the weights that are
applied to the past 8 values of the time series (i.e. <span
class="math inline">\(y_{t-1}\)</span>, <span
class="math inline">\(y_{t-2}\)</span>, <span
class="math inline">\(y_{t-3}\)</span>, <span
class="math inline">\(y_{t-4}\)</span>, <span
class="math inline">\(y_{t-5}\)</span>, <span
class="math inline">\(y_{t-6}\)</span>, <span
class="math inline">\(y_{t-7}\)</span>, <span
class="math inline">\(y_{t-8}\)</span>) in order to predict the next
value of the time series (<span
class="math inline">\(\hat{y}_t\)</span>). In this case, the
coefficients are as follows:</p>
<p>These coefficients can be used to write the ARIMA (8,0,0) equation as
follows:</p>
<p><span class="math inline">\(\hat{y}t = \alpha_1 y{t-1} + \alpha_2
y_{t-2} + \alpha_3 y_{t-3} + \alpha_4 y_{t-4} + \alpha_5 y_{t-5} +
\alpha_6 y_{t-6} + \alpha_7 y_{t-7} + \alpha_8 y_{t-8} +
\beta_0\)</span></p>
<p><span class="math inline">\(\begin{aligned} \hat{y}t &amp;= 1.0562
\cdot y_{t-1} - 0.2312 \cdot y_{t-2} + 0.0948 \cdot y_{t-3} + 0.0779
\cdot y_{t-4} - 0.1035 \cdot y_{t-5} + 0.1343 \cdot y_{t-6} + 0.3918
\cdot y_{t-7} - 0.4517 \cdot y_{t-8} + 2924.354
\end{aligned}\)</span></p>
<p>This equation can be used to predict the next value of the time
series, <span class="math inline">\(\hat{y}_t\)</span>, based on the
past 8 values of the time series. The coefficients in the equation
represent the relative importance of each of the past values in
predicting the next value.</p>
<p>Plotting the fitted values alongside the positive covid cases:</p>
<pre class="r"><code>ar = fitted(reg1)
ggplot(sub_df, aes(x=test_date, y=new_positives)) + 
  geom_point(alpha = 20/100, color = &quot;red&quot;) + 
  scale_x_date(date_labels = &quot;%m-%Y&quot;,date_breaks = &quot;1 month&quot;) +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(title = &quot;Scatter Plot of Daily Postive Cases in New York City from 2020-2022
       with ARIMA trend line&quot;, x= &quot;Test Date&quot;,
       y = &#39;Positive Cases Detected&#39;) +
  geom_line(aes(y=ar,color = &quot;ARIMA trend line&quot;)) +  
  scale_color_manual(values = c(&quot;ARIMA trend line&quot; = &quot;black&quot;),
                                          labels = &quot;Fitted Arima Model&quot;) </code></pre>
<p><img src="Final-Report-Main_files/figure-html/unnamed-chunk-24-1.png" width="90%" /></p>
</div>
<div id="discussions" class="section level2">
<h2>Discussions</h2>
</div>
<div id="limitations" class="section level2">
<h2>Limitations</h2>
</div>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3,h4",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
