---
title: "r_final_proj"
output: github_document
---

```{r setup, include=FALSE}
require(data.table)
require(tidycensus)
require(ggplot2)
library(tidyverse)
library(ggridges)
library(patchwork)
library(readxl)
library(readr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Importing Census Data (df = ny_df)

```{r census_data}
census_api_key("aa512886c5449a582d837da8d3a07af66a043fe5")

census_data <- load_variables(2019, "acs5", cache=T)
fwrite(census_data, "census_variables.csv")

vars <- c(tpop = 'P001001',
          medage = 'P013001',
          wpop = 'P003002',
          bpop = 'P003003',
          apop = 'P003005',
          hpop = 'P004003')

ny_df <- get_decennial(state = "ny", 
                       geography = "county",
                       variables = vars,
                       geometry = T,
                       output = "wide")

ny_df = ny_df %>%
  mutate(
    county = gsub(" County, New York","",NAME))
```

## Importing 2019-2022 Health Ranking Data 

1. Import excel
2. Select sheets: outcomes & factors subrankings, additional measure data (mainly for demographics info)
3. Selected necessary variables from each sheet
4. Renamed variables 
5. Merged dataframe generated from each sheet

```{r 2019}
ny_hr2019 = read_excel('grace/ny_hr19.xls', sheet = 'Outcomes & Factors SubRankings', skip = 1) %>% 
  janitor::clean_names() %>% 
  slice(-c(1)) %>% 
  select(-ends_with("z"), -fips)

ny_demo2019 = read_excel('grace/ny_hr19.xls', sheet = 'Additional Measure Data', skip = 1) %>% 
  janitor::clean_names() %>% 
  slice(-c(1)) %>% 
  select('county', 'household_income', 'number_african_american', 'number_american_indian_alaskan_native', 'number_asian', 'number_native_hawaiian_other_pacific_islander', 'number_hispanic', 'number_non_hispanic_white') %>% 
  rename(median_income = household_income, n_black = number_african_american, n_american_ind_al_native = number_american_indian_alaskan_native, n_asian = number_asian, n_nat_ha_other_pac_is = number_native_hawaiian_other_pacific_islander, n_latino = number_hispanic, n_white = number_non_hispanic_white)

ny_hr2019_fin = merge(x=ny_hr2019, y=ny_demo2019, 
          by="county", all.x=TRUE)
```
