---
title: "Final Report"
output: html_document
date: "2022-12-02"
---

Motivation: 

Studying the change in COVID-19 trend in New York State for each county, and examining how COVID-19 is spatially autocorrelated across different counties and whether health behaviors and socioeconomic (SES) factors are associated with this change, can be helpful to public health officials in several ways.

First, understanding the spatial patterns of COVID-19 trends can help public health officials to identify areas that are at higher risk for the spread of the virus. This information can be used to target interventions and resources to these areas in order to reduce the spread of COVID-19 and protect the health of the population.

Second, examining the relationship between health behaviors and SES factors and the change in COVID-19 trend can help public health officials to identify potential risk factors for the spread of the virus. This information can be used to develop targeted interventions and policies that aim to reduce the risk of COVID-19 transmission by addressing these factors.

Overall, studying the change in COVID-19 trend in New York State for each county, and examining spatial autocorrelation and the relationship with health behaviors and SES factors, can provide valuable insights that can help public health officials to better understand the spread of COVID-19 and take effective action to reduce the risk of transmission

